package com.td.admin.mapper;

import java.util.List;
import java.util.Map;

import com.td.admin.entity.FinCalender;

public interface FinCalenderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_CALENDER
     *
     * @mbggenerated Tue Aug 20 09:29:36 CST 2013
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_CALENDER
     *
     * @mbggenerated Tue Aug 20 09:29:36 CST 2013
     */
    int insert(FinCalender record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_CALENDER
     *
     * @mbggenerated Tue Aug 20 09:29:36 CST 2013
     */
    int insertSelective(FinCalender record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_CALENDER
     *
     * @mbggenerated Tue Aug 20 09:29:36 CST 2013
     */
    FinCalender selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_CALENDER
     *
     * @mbggenerated Tue Aug 20 09:29:36 CST 2013
     */
    int updateByPrimaryKeySelective(FinCalender record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_CALENDER
     *
     * @mbggenerated Tue Aug 20 09:29:36 CST 2013
     */
    int updateByPrimaryKey(FinCalender record);

	List<FinCalender> find(Map<String, Object> map);
	
	 List<FinCalender> queryCalendar(FinCalender calendar) ;
	 
	 List<FinCalender> selectByDate(FinCalender calendar) ;
}