package com.td.admin.mapper;

import java.util.Map;

import com.td.admin.entity.FinSalesHierarchyRelation;

public interface FinSalesHierarchyRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_SALES_HIERARCHY_RELATION
     *
     * @mbggenerated Thu Dec 12 10:58:31 CST 2013
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_SALES_HIERARCHY_RELATION
     *
     * @mbggenerated Thu Dec 12 10:58:31 CST 2013
     */
    int insert(FinSalesHierarchyRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_SALES_HIERARCHY_RELATION
     *
     * @mbggenerated Thu Dec 12 10:58:31 CST 2013
     */
    int insertSelective(FinSalesHierarchyRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_SALES_HIERARCHY_RELATION
     *
     * @mbggenerated Thu Dec 12 10:58:31 CST 2013
     */
    FinSalesHierarchyRelation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_SALES_HIERARCHY_RELATION
     *
     * @mbggenerated Thu Dec 12 10:58:31 CST 2013
     */
    int updateByPrimaryKeySelective(FinSalesHierarchyRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_SALES_HIERARCHY_RELATION
     *
     * @mbggenerated Thu Dec 12 10:58:31 CST 2013
     */
    int updateByPrimaryKey(FinSalesHierarchyRelation record);

	void deleteByMap(Map<String, Object> condMap);

	void deleteByGroupid(Long id);

	int queryRelationByMap(Map<String, Object> condMap);

	void deleteByUmid(String userUmid);
}