package com.td.admin.mapper;

import java.util.List;

import com.td.admin.entity.FinSalesHierarchyUser;

public interface FinSalesHierarchyUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_SALES_HIERARCHY_USER
     *
     * @mbggenerated Thu Dec 12 10:58:31 CST 2013
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_SALES_HIERARCHY_USER
     *
     * @mbggenerated Thu Dec 12 10:58:31 CST 2013
     */
    int insert(FinSalesHierarchyUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_SALES_HIERARCHY_USER
     *
     * @mbggenerated Thu Dec 12 10:58:31 CST 2013
     */
    int insertSelective(FinSalesHierarchyUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_SALES_HIERARCHY_USER
     *
     * @mbggenerated Thu Dec 12 10:58:31 CST 2013
     */
    FinSalesHierarchyUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_SALES_HIERARCHY_USER
     *
     * @mbggenerated Thu Dec 12 10:58:31 CST 2013
     */
    int updateByPrimaryKeySelective(FinSalesHierarchyUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_SALES_HIERARCHY_USER
     *
     * @mbggenerated Thu Dec 12 10:58:31 CST 2013
     */
    int updateByPrimaryKey(FinSalesHierarchyUser record);

	List<FinSalesHierarchyUser> findByGroupId(Long groupId);

	FinSalesHierarchyUser findByCode(String code);

	FinSalesHierarchyUser findByUserUmId(String userUmId);

	void deleteByUmid(String userUmid);
}