package com.td.admin.mapper;

import java.util.List;

import com.td.admin.entity.FinSalesHierarchyGroup;

public interface FinSalesHierarchyGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_SALES_HIERARCHY_GROUP
     *
     * @mbggenerated Thu Dec 12 10:58:31 CST 2013
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_SALES_HIERARCHY_GROUP
     *
     * @mbggenerated Thu Dec 12 10:58:31 CST 2013
     */
    int insert(FinSalesHierarchyGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_SALES_HIERARCHY_GROUP
     *
     * @mbggenerated Thu Dec 12 10:58:31 CST 2013
     */
    int insertSelective(FinSalesHierarchyGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_SALES_HIERARCHY_GROUP
     *
     * @mbggenerated Thu Dec 12 10:58:31 CST 2013
     */
    FinSalesHierarchyGroup selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_SALES_HIERARCHY_GROUP
     *
     * @mbggenerated Thu Dec 12 10:58:31 CST 2013
     */
    int updateByPrimaryKeySelective(FinSalesHierarchyGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_SALES_HIERARCHY_GROUP
     *
     * @mbggenerated Thu Dec 12 10:58:31 CST 2013
     */
    int updateByPrimaryKey(FinSalesHierarchyGroup record);

	List<FinSalesHierarchyGroup> findBySuperGroupId(Long superGroupId);

	List<FinSalesHierarchyGroup> findBySuperCode(String code);
}