package com.td.admin.mapper;

import java.util.List;

import com.td.admin.entity.SysCacheInfo;

public interface SysCacheInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_SYSTEM_CACHEINFO
     *
     * @mbggenerated Fri Aug 09 14:44:31 CST 2013
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_SYSTEM_CACHEINFO
     *
     * @mbggenerated Fri Aug 09 14:44:31 CST 2013
     */
    int insert(SysCacheInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_SYSTEM_CACHEINFO
     *
     * @mbggenerated Fri Aug 09 14:44:31 CST 2013
     */
    int insertSelective(SysCacheInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_SYSTEM_CACHEINFO
     *
     * @mbggenerated Fri Aug 09 14:44:31 CST 2013
     */
    SysCacheInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_SYSTEM_CACHEINFO
     *
     * @mbggenerated Fri Aug 09 14:44:31 CST 2013
     */
    int updateByPrimaryKeySelective(SysCacheInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_SYSTEM_CACHEINFO
     *
     * @mbggenerated Fri Aug 09 14:44:31 CST 2013
     */
    int updateByPrimaryKey(SysCacheInfo record);
    
    Long getPagingCount(SysCacheInfo record);
   
     List<SysCacheInfo> queryCache(SysCacheInfo record);
}