package com.td.admin.mapper;

import java.util.List;
import java.util.Map;

import com.td.admin.entity.SysDicItem;

public interface SysDicItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_DIC_ITEM
     *
     * @mbggenerated Fri Aug 09 10:19:21 CST 2013
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_DIC_ITEM
     *
     * @mbggenerated Fri Aug 09 10:19:21 CST 2013
     */
    int insert(SysDicItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_DIC_ITEM
     *
     * @mbggenerated Fri Aug 09 10:19:21 CST 2013
     */
    int insertSelective(SysDicItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_DIC_ITEM
     *
     * @mbggenerated Fri Aug 09 10:19:21 CST 2013
     */
    SysDicItem selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_DIC_ITEM
     *
     * @mbggenerated Fri Aug 09 10:19:21 CST 2013
     */
    int updateByPrimaryKeySelective(SysDicItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_DIC_ITEM
     *
     * @mbggenerated Fri Aug 09 10:19:21 CST 2013
     */
    int updateByPrimaryKey(SysDicItem record);
    
    //******** extends ***********************//
    
    List<SysDicItem> getDictItems(SysDicItem record);
    
    /**
     * 根据dicKey和parentDictItemId获取对应的字典项
     * @param params	参数包括字典英文名（dicKey）/父字典项的Key（parentDicItemKey）
     * @return
     */
    List<SysDicItem> getDictItemsByKey(Map<String,String> params);
    
    SysDicItem selectByBusinessKey(SysDicItem params);
    
    List<SysDicItem> selectChildrenByDicIdAndParentId(SysDicItem params);
    //得到所有的产品类别
    List<SysDicItem> findAllCategoryList(SysDicItem params);
    
    List<SysDicItem> findByDicName(String dicName);
    List<SysDicItem> selectByMap(Map<String,Object> params);
    
    List<SysDicItem> getDictItemsByDicName(String dicName);

}