package com.td.admin.mapper;

import java.util.List;

import com.td.admin.entity.SysEmailServerConfig;
import com.td.common.bean.PageBean;

public interface SysEmailServerConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_EMAIL_SERVER_CONFIG
     *
     * @mbggenerated Fri Aug 09 11:26:31 CST 2013
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_EMAIL_SERVER_CONFIG
     *
     * @mbggenerated Fri Aug 09 11:26:31 CST 2013
     */
    int insert(SysEmailServerConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_EMAIL_SERVER_CONFIG
     *
     * @mbggenerated Fri Aug 09 11:26:31 CST 2013
     */
    int insertSelective(SysEmailServerConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_EMAIL_SERVER_CONFIG
     *
     * @mbggenerated Fri Aug 09 11:26:31 CST 2013
     */
    SysEmailServerConfig selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_EMAIL_SERVER_CONFIG
     *
     * @mbggenerated Fri Aug 09 11:26:31 CST 2013
     */
    int updateByPrimaryKeySelective(SysEmailServerConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_EMAIL_SERVER_CONFIG
     *
     * @mbggenerated Fri Aug 09 11:26:31 CST 2013
     */
    int updateByPrimaryKey(SysEmailServerConfig record);
    
    SysEmailServerConfig find(String code);
    
    Long queryTotalCount();
    
    List<SysEmailServerConfig> queryMailServers(PageBean pageBean);
    
}