package com.td.admin.mapper;

import java.util.List;

import com.td.admin.entity.SysEmailSendJobInput;

public interface SysEmailSendJobInputMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_EMAIL_SEND_JOB_INPUT
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_EMAIL_SEND_JOB_INPUT
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    int insert(SysEmailSendJobInput record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_EMAIL_SEND_JOB_INPUT
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    int insertSelective(SysEmailSendJobInput record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_EMAIL_SEND_JOB_INPUT
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    SysEmailSendJobInput selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_EMAIL_SEND_JOB_INPUT
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    int updateByPrimaryKeySelective(SysEmailSendJobInput record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_EMAIL_SEND_JOB_INPUT
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    int updateByPrimaryKey(SysEmailSendJobInput record);

	List<SysEmailSendJobInput> findValid();

	List<SysEmailSendJobInput> findNoSend();
}