package com.td.admin.mapper;

import java.util.List;

import com.td.admin.entity.SysEmailReceiveJobInput;

public interface SysEmailReceiveJobInputMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_EMAIL_RECEIVE_JOB_INPUT
     *
     * @mbggenerated Fri Oct 18 16:29:23 CST 2013
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_EMAIL_RECEIVE_JOB_INPUT
     *
     * @mbggenerated Fri Oct 18 16:29:23 CST 2013
     */
    int insert(SysEmailReceiveJobInput record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_EMAIL_RECEIVE_JOB_INPUT
     *
     * @mbggenerated Fri Oct 18 16:29:23 CST 2013
     */
    int insertSelective(SysEmailReceiveJobInput record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_EMAIL_RECEIVE_JOB_INPUT
     *
     * @mbggenerated Fri Oct 18 16:29:23 CST 2013
     */
    SysEmailReceiveJobInput selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_EMAIL_RECEIVE_JOB_INPUT
     *
     * @mbggenerated Fri Oct 18 16:29:23 CST 2013
     */
    int updateByPrimaryKeySelective(SysEmailReceiveJobInput record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_EMAIL_RECEIVE_JOB_INPUT
     *
     * @mbggenerated Fri Oct 18 16:29:23 CST 2013
     */
    int updateByPrimaryKey(SysEmailReceiveJobInput record);

	List<SysEmailReceiveJobInput> findByReceive();
}