package com.td.admin.mapper;

import java.util.List;
import java.util.Map;

import com.td.admin.entity.SysEmailTemplate;

public interface SysEmailTemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_EMAIL_TEMPLATE
     *
     * @mbggenerated Fri Aug 09 10:57:23 CST 2013
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_EMAIL_TEMPLATE
     *
     * @mbggenerated Fri Aug 09 10:57:23 CST 2013
     */
    int insert(SysEmailTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_EMAIL_TEMPLATE
     *
     * @mbggenerated Fri Aug 09 10:57:23 CST 2013
     */
    int insertSelective(SysEmailTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_EMAIL_TEMPLATE
     *
     * @mbggenerated Fri Aug 09 10:57:23 CST 2013
     */
    SysEmailTemplate selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_EMAIL_TEMPLATE
     *
     * @mbggenerated Fri Aug 09 10:57:23 CST 2013
     */
    int updateByPrimaryKeySelective(SysEmailTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_EMAIL_TEMPLATE
     *
     * @mbggenerated Fri Aug 09 10:57:23 CST 2013
     */
    int updateByPrimaryKey(SysEmailTemplate record);
    
    Long queryTotalCount(SysEmailTemplate emailTemp);

    List<SysEmailTemplate> queryMailTemplate(SysEmailTemplate emailTemp);

	SysEmailTemplate findByCode(String timeoutTaskEmailTempCode);
    
    SysEmailTemplate findEmailTemplate(Map condidate);
    List<SysEmailTemplate> getAllMails();
    List<SysEmailTemplate> getMailTemplatesByCodeOrTitle(String codeOrTitle);
    
    SysEmailTemplate getMailTemplateByCode(String code);

}