package com.td.admin.mapper;

import java.util.List;
import java.util.Map;

import com.td.admin.entity.SysJobConfig;

public interface SysJobConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_JOB_CONFIG
     *
     * @mbggenerated Fri Aug 09 14:44:09 CST 2013
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_JOB_CONFIG
     *
     * @mbggenerated Fri Aug 09 14:44:09 CST 2013
     */
    int insert(SysJobConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_JOB_CONFIG
     *
     * @mbggenerated Fri Aug 09 14:44:09 CST 2013
     */
    int insertSelective(SysJobConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_JOB_CONFIG
     *
     * @mbggenerated Fri Aug 09 14:44:09 CST 2013
     */
    SysJobConfig selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_JOB_CONFIG
     *
     * @mbggenerated Fri Aug 09 14:44:09 CST 2013
     */
    int updateByPrimaryKeySelective(SysJobConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_JOB_CONFIG
     *
     * @mbggenerated Fri Aug 09 14:44:09 CST 2013
     */
    int updateByPrimaryKey(SysJobConfig record);
    
    int updateByjKey(SysJobConfig record);
    
    List<SysJobConfig> findValidJob();
    
    Long getPagingCount(SysJobConfig jobConfig);
    
    List<SysJobConfig> queryJobConfig(SysJobConfig record);

    List<SysJobConfig> getPagingList(Map<String, Object> condMap);

    List<String> findJobKeyByJobName(Map<String, Object> condMap);
}