package com.td.admin.mapper;

import java.util.List;
import java.util.Map;

import com.td.admin.entity.SysJobTempJobInput;

public interface SysJobTempJobInputMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_JOB_TEMPJOBINPUT
     *
     * @mbggenerated Fri Aug 09 14:39:11 CST 2013
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_JOB_TEMPJOBINPUT
     *
     * @mbggenerated Fri Aug 09 14:39:11 CST 2013
     */
    int insert(SysJobTempJobInput record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_JOB_TEMPJOBINPUT
     *
     * @mbggenerated Fri Aug 09 14:39:11 CST 2013
     */
    int insertSelective(SysJobTempJobInput record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_JOB_TEMPJOBINPUT
     *
     * @mbggenerated Fri Aug 09 14:39:11 CST 2013
     */
    SysJobTempJobInput selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_JOB_TEMPJOBINPUT
     *
     * @mbggenerated Fri Aug 09 14:39:11 CST 2013
     */
    int updateByPrimaryKeySelective(SysJobTempJobInput record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_JOB_TEMPJOBINPUT
     *
     * @mbggenerated Fri Aug 09 14:39:11 CST 2013
     */
    int updateByPrimaryKey(SysJobTempJobInput record);
    
    
    List<SysJobTempJobInput> findValid();

    Long getPagingCount(SysJobTempJobInput tempJobInput);
    
    List<SysJobTempJobInput> queryJobTemp(SysJobTempJobInput record);

    List<SysJobTempJobInput> getPagingList(Map<String, Object> condMap);
    
    int updateJobConfigTemp(Long id);
    /*插入一条临时任务*/
    int insertFinJobTempJobInput(SysJobTempJobInput tempJob);
}