package com.td.admin.mapper;

import java.util.List;
import java.util.Map;

import com.td.admin.entity.SysOaTask;

public interface SysOaTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OA_TASK
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OA_TASK
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    int insert(SysOaTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OA_TASK
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    int insertSelective(SysOaTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OA_TASK
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    SysOaTask selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OA_TASK
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    int updateByPrimaryKeySelective(SysOaTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OA_TASK
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    int updateByPrimaryKey(SysOaTask record);
    
    List<SysOaTask> queryOaTask(SysOaTask record);

	Long queryTotalCount(SysOaTask record);
	
	SysOaTask getOaTask(Map condition);
	
	List<SysOaTask> approveHistory(Map condition);
	
	List<SysOaTask> getOaTaskByInstanceId(SysOaTask record);
	
}