package com.td.admin.mapper;

import java.util.List;

import com.td.admin.entity.SysOaTemplate;

public interface SysOaTemplateMapper {
	 /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OA_OATEMPLATE
     *
     * @mbggenerated Mon Aug 12 18:40:35 CST 2013
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OA_OATEMPLATE
     *
     * @mbggenerated Mon Aug 12 18:40:35 CST 2013
     */
    int insert(SysOaTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OA_OATEMPLATE
     *
     * @mbggenerated Mon Aug 12 18:40:35 CST 2013
     */
    int insertSelective(SysOaTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OA_OATEMPLATE
     *
     * @mbggenerated Mon Aug 12 18:40:35 CST 2013
     */
    SysOaTemplate selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OA_OATEMPLATE
     *
     * @mbggenerated Mon Aug 12 18:40:35 CST 2013
     */
    int updateByPrimaryKeySelective(SysOaTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OA_OATEMPLATE
     *
     * @mbggenerated Mon Aug 12 18:40:35 CST 2013
     */
    int updateByPrimaryKey(SysOaTemplate record);
    
    
    Long queryTotalCount(SysOaTemplate record);
    
    List<SysOaTemplate> queryApprovalTemplate(SysOaTemplate record);
    
    SysOaTemplate selectBycode(String code);
    
    SysOaTemplate selectMasterSlaveByCode(String code);
}