package com.td.admin.mapper;

import java.util.List;
import java.util.Map;

import com.td.admin.entity.SysProcessConfig;

public interface SysProcessConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_PROCESS_CONFIG
     *
     * @mbggenerated Wed Aug 21 11:03:45 CST 2013
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_PROCESS_CONFIG
     *
     * @mbggenerated Wed Aug 21 11:03:45 CST 2013
     */
    int insert(SysProcessConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_PROCESS_CONFIG
     *
     * @mbggenerated Wed Aug 21 11:03:45 CST 2013
     */
    int insertSelective(SysProcessConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_PROCESS_CONFIG
     *
     * @mbggenerated Wed Aug 21 11:03:45 CST 2013
     */
    SysProcessConfig selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_PROCESS_CONFIG
     *
     * @mbggenerated Wed Aug 21 11:03:45 CST 2013
     */
    int updateByPrimaryKeySelective(SysProcessConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_PROCESS_CONFIG
     *
     * @mbggenerated Wed Aug 21 11:03:45 CST 2013
     */
    int updateByPrimaryKey(SysProcessConfig record);
    
    Long queryTotalCount(SysProcessConfig record);
    
    List<SysProcessConfig> queryProcessConfig(SysProcessConfig record);
    
	SysProcessConfig findByCode(String code);
    
    SysProcessConfig getFinProcessConfig(Map<String,Object> condition);
    

    SysProcessConfig findProcessConfig(Map condidate);
    
    List<SysProcessConfig> queryFinProcessConfig();
    
    List<SysProcessConfig> queryFinProcessConfigByName(SysProcessConfig config);
}