package com.td.admin.mapper;

import java.util.List;
import java.util.Map;

import com.td.admin.entity.SysProcessConfig;
import com.td.admin.entity.SysProcessTaskConfig;

public interface SysProcessTaskConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_TASK_CONFIG
     *
     * @mbggenerated Wed Aug 21 10:18:24 CST 2013
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_TASK_CONFIG
     *
     * @mbggenerated Wed Aug 21 10:18:24 CST 2013
     */
    int insert(SysProcessTaskConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_TASK_CONFIG
     *
     * @mbggenerated Wed Aug 21 10:18:24 CST 2013
     */
    int insertSelective(SysProcessTaskConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_TASK_CONFIG
     *
     * @mbggenerated Wed Aug 21 10:18:24 CST 2013  
     */
    SysProcessTaskConfig selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_TASK_CONFIG
     *
     * @mbggenerated Wed Aug 21 10:18:24 CST 2013
     */
    int updateByPrimaryKeySelective(SysProcessTaskConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_TASK_CONFIG
     *
     * @mbggenerated Wed Aug 21 10:18:24 CST 2013
     */
    int updateByPrimaryKey(SysProcessTaskConfig record);

	Long queryTotalCount(SysProcessTaskConfig record);

	List<SysProcessConfig> queryTaskConfig(SysProcessTaskConfig record);
	
	SysProcessTaskConfig getFinTaskConfig(Map<String,Object> condition);
}