package com.td.admin.mapper;

import com.td.admin.entity.SysSequenceSub;

public interface SysSequenceSubMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_SEQUENCE_SHEET
     *
     * @mbggenerated Thu Jan 16 15:31:41 CST 2014
     */
    int deleteByPrimaryKey(String seqSubName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_SEQUENCE_SHEET
     *
     * @mbggenerated Thu Jan 16 15:31:41 CST 2014
     */
    int insert(SysSequenceSub record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_SEQUENCE_SHEET
     *
     * @mbggenerated Thu Jan 16 15:31:41 CST 2014
     */
    int insertSelective(SysSequenceSub record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_SEQUENCE_SHEET
     *
     * @mbggenerated Thu Jan 16 15:31:41 CST 2014
     */
    SysSequenceSub selectByPrimaryKey(String seqSubName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_SEQUENCE_SHEET
     *
     * @mbggenerated Thu Jan 16 15:31:41 CST 2014
     */
    int updateByPrimaryKeySelective(SysSequenceSub record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_SEQUENCE_SHEET
     *
     * @mbggenerated Thu Jan 16 15:31:41 CST 2014
     */
    int updateByPrimaryKey(SysSequenceSub record);
    
    /**
     * 获得当前的数字
     * @param record 中只需要：seqSubName
     * @return
     */
    Integer selectSeqSubCurrNum(SysSequenceSub record);
    
    /**
     * 获得下一个数字
     * @param record
     * @return 中只需要：seqSubName
     */
    Integer selectSeqSubNextNum(SysSequenceSub record);
    
    /**
     * 获得当前的序列号
     * @param record 中只需要：seqSubName,connectSign
     * @return
     */
    String selectSeqSubCurrVal(SysSequenceSub record);
    
    /**
     * 获得下一个序列号
     * @param record
     * @return 中只需要：seqSubName,connectSign
     */
    String selectSeqSubNextVal(SysSequenceSub record);
    
    /**
     * 设置序列号
     * @param record 中只需要：seqSubName, curValue, remark connectSign
     * @return
     */
    String selectSeqSubSetVal(SysSequenceSub record);
}