package com.td.admin.mapper;

import com.td.admin.entity.SysSequence;

public interface SysSequenceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_SEQUENCE
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    int deleteByPrimaryKey(String seqName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_SEQUENCE
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    int insert(SysSequence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_SEQUENCE
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    int insertSelective(SysSequence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_SEQUENCE
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    SysSequence selectByPrimaryKey(String seqName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_SEQUENCE
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    int updateByPrimaryKeySelective(SysSequence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIN_SEQUENCE
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    int updateByPrimaryKey(SysSequence record);
    
    /**
     * 得到序列的当前值 
     * @param record (通过seqName获取)
     * @return
     */
    String selectSeqCurrVal(SysSequence record);
    
    /**
     * 获得下一个序列值
     * @param record (通过seqName获取)
     * @return
     */
    String selectSeqNextVal(SysSequence record);
    
    /**
     * 设置序列的起始值
     * @param record(通过seqName, increment)
     * @return
     */
    String selectSeqSetVal(SysSequence record);
}