package com.td.admin.entity;

import java.util.Date;

public class FinCalender {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Fin_Calender.id
     *
     * @mbggenerated Tue Aug 20 09:29:36 CST 2013
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Fin_Calender.date
     *
     * @mbggenerated Tue Aug 20 09:29:36 CST 2013
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Fin_Calender.type
     *
     * @mbggenerated Tue Aug 20 09:29:36 CST 2013
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Fin_Calender.MTime
     *
     * @mbggenerated Tue Aug 20 09:29:36 CST 2013
     */
    private Date mtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Fin_Calender.CTime
     *
     * @mbggenerated Tue Aug 20 09:29:36 CST 2013
     */
    private Date ctime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Fin_Calender.id
     *
     * @return the value of Fin_Calender.id
     *
     * @mbggenerated Tue Aug 20 09:29:36 CST 2013
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Fin_Calender.id
     *
     * @param id the value for Fin_Calender.id
     *
     * @mbggenerated Tue Aug 20 09:29:36 CST 2013
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Fin_Calender.date
     *
     * @return the value of Fin_Calender.date
     *
     * @mbggenerated Tue Aug 20 09:29:36 CST 2013
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Fin_Calender.date
     *
     * @param date the value for Fin_Calender.date
     *
     * @mbggenerated Tue Aug 20 09:29:36 CST 2013
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Fin_Calender.type
     *
     * @return the value of Fin_Calender.type
     *
     * @mbggenerated Tue Aug 20 09:29:36 CST 2013
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Fin_Calender.type
     *
     * @param type the value for Fin_Calender.type
     *
     * @mbggenerated Tue Aug 20 09:29:36 CST 2013
     */
    public void setType(String type) {
        this.type = type;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Fin_Calender.MTime
     *
     * @return the value of Fin_Calender.MTime
     *
     * @mbggenerated Tue Aug 20 09:29:36 CST 2013
     */
    public Date getMtime() {
        return mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Fin_Calender.MTime
     *
     * @param mtime the value for Fin_Calender.MTime
     *
     * @mbggenerated Tue Aug 20 09:29:36 CST 2013
     */
    public void setMtime(Date mtime) {
        this.mtime = mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Fin_Calender.CTime
     *
     * @return the value of Fin_Calender.CTime
     *
     * @mbggenerated Tue Aug 20 09:29:36 CST 2013
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Fin_Calender.CTime
     *
     * @param ctime the value for Fin_Calender.CTime
     *
     * @mbggenerated Tue Aug 20 09:29:36 CST 2013
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }
    private String year;

	public String getYear() {
		return year;
	}

	public void setYear(String year) {
		this.year = year;
	}
    
}