package com.td.admin.entity;

import java.util.Date;

public class FinSalesHierarchyGroup {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_SALES_HIERARCHY_GROUP.id
     *
     * @mbggenerated Thu Dec 12 10:58:31 CST 2013
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_SALES_HIERARCHY_GROUP.groupName
     *
     * @mbggenerated Thu Dec 12 10:58:31 CST 2013
     */
    private String groupname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_SALES_HIERARCHY_GROUP.superiorId
     *
     * @mbggenerated Thu Dec 12 10:58:31 CST 2013
     */
    private Long superiorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_SALES_HIERARCHY_GROUP.description
     *
     * @mbggenerated Thu Dec 12 10:58:31 CST 2013
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_SALES_HIERARCHY_GROUP.MTime
     *
     * @mbggenerated Thu Dec 12 10:58:31 CST 2013
     */
    private Date mtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_SALES_HIERARCHY_GROUP.CTime
     *
     * @mbggenerated Thu Dec 12 10:58:31 CST 2013
     */
    private Date ctime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_SALES_HIERARCHY_GROUP.id
     *
     * @return the value of FIN_SALES_HIERARCHY_GROUP.id
     *
     * @mbggenerated Thu Dec 12 10:58:31 CST 2013
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_SALES_HIERARCHY_GROUP.id
     *
     * @param id the value for FIN_SALES_HIERARCHY_GROUP.id
     *
     * @mbggenerated Thu Dec 12 10:58:31 CST 2013
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_SALES_HIERARCHY_GROUP.groupName
     *
     * @return the value of FIN_SALES_HIERARCHY_GROUP.groupName
     *
     * @mbggenerated Thu Dec 12 10:58:31 CST 2013
     */
    public String getGroupname() {
        return groupname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_SALES_HIERARCHY_GROUP.groupName
     *
     * @param groupname the value for FIN_SALES_HIERARCHY_GROUP.groupName
     *
     * @mbggenerated Thu Dec 12 10:58:31 CST 2013
     */
    public void setGroupname(String groupname) {
        this.groupname = groupname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_SALES_HIERARCHY_GROUP.superiorId
     *
     * @return the value of FIN_SALES_HIERARCHY_GROUP.superiorId
     *
     * @mbggenerated Thu Dec 12 10:58:31 CST 2013
     */
    public Long getSuperiorid() {
        return superiorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_SALES_HIERARCHY_GROUP.superiorId
     *
     * @param superiorid the value for FIN_SALES_HIERARCHY_GROUP.superiorId
     *
     * @mbggenerated Thu Dec 12 10:58:31 CST 2013
     */
    public void setSuperiorid(Long superiorid) {
        this.superiorid = superiorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_SALES_HIERARCHY_GROUP.description
     *
     * @return the value of FIN_SALES_HIERARCHY_GROUP.description
     *
     * @mbggenerated Thu Dec 12 10:58:31 CST 2013
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_SALES_HIERARCHY_GROUP.description
     *
     * @param description the value for FIN_SALES_HIERARCHY_GROUP.description
     *
     * @mbggenerated Thu Dec 12 10:58:31 CST 2013
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_SALES_HIERARCHY_GROUP.MTime
     *
     * @return the value of FIN_SALES_HIERARCHY_GROUP.MTime
     *
     * @mbggenerated Thu Dec 12 10:58:31 CST 2013
     */
    public Date getMtime() {
        return mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_SALES_HIERARCHY_GROUP.MTime
     *
     * @param mtime the value for FIN_SALES_HIERARCHY_GROUP.MTime
     *
     * @mbggenerated Thu Dec 12 10:58:31 CST 2013
     */
    public void setMtime(Date mtime) {
        this.mtime = mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_SALES_HIERARCHY_GROUP.CTime
     *
     * @return the value of FIN_SALES_HIERARCHY_GROUP.CTime
     *
     * @mbggenerated Thu Dec 12 10:58:31 CST 2013
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_SALES_HIERARCHY_GROUP.CTime
     *
     * @param ctime the value for FIN_SALES_HIERARCHY_GROUP.CTime
     *
     * @mbggenerated Thu Dec 12 10:58:31 CST 2013
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }
}