package com.td.admin.entity;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

public class FinSalesHierarchyUser implements Serializable{
	/**
	 * 序列标识
	 */
	private static final long serialVersionUID = 1L;
	//销售层级子用户集合
	private List<FinSalesHierarchyUser> underlingSalersList;
	
	private Long relationid;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_SALES_HIERARCHY_USER.id
     *
     * @mbggenerated Thu Dec 12 10:58:31 CST 2013
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_SALES_HIERARCHY_USER.code
     *
     * @mbggenerated Thu Dec 12 10:58:31 CST 2013
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_SALES_HIERARCHY_USER.userUmId
     *
     * @mbggenerated Thu Dec 12 10:58:31 CST 2013
     */
    private String userumid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_SALES_HIERARCHY_USER.userName
     *
     * @mbggenerated Thu Dec 12 10:58:31 CST 2013
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_SALES_HIERARCHY_USER.MTime
     *
     * @mbggenerated Thu Dec 12 10:58:31 CST 2013
     */
    private Date mtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_SALES_HIERARCHY_USER.CTime
     *
     * @mbggenerated Thu Dec 12 10:58:31 CST 2013
     */
    private Date ctime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_SALES_HIERARCHY_USER.id
     *
     * @return the value of FIN_SALES_HIERARCHY_USER.id
     *
     * @mbggenerated Thu Dec 12 10:58:31 CST 2013
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_SALES_HIERARCHY_USER.id
     *
     * @param id the value for FIN_SALES_HIERARCHY_USER.id
     *
     * @mbggenerated Thu Dec 12 10:58:31 CST 2013
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_SALES_HIERARCHY_USER.code
     *
     * @return the value of FIN_SALES_HIERARCHY_USER.code
     *
     * @mbggenerated Thu Dec 12 10:58:31 CST 2013
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_SALES_HIERARCHY_USER.code
     *
     * @param code the value for FIN_SALES_HIERARCHY_USER.code
     *
     * @mbggenerated Thu Dec 12 10:58:31 CST 2013
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_SALES_HIERARCHY_USER.userUmId
     *
     * @return the value of FIN_SALES_HIERARCHY_USER.userUmId
     *
     * @mbggenerated Thu Dec 12 10:58:31 CST 2013
     */
    public String getUserumid() {
        return userumid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_SALES_HIERARCHY_USER.userUmId
     *
     * @param userumid the value for FIN_SALES_HIERARCHY_USER.userUmId
     *
     * @mbggenerated Thu Dec 12 10:58:31 CST 2013
     */
    public void setUserumid(String userumid) {
        this.userumid = userumid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_SALES_HIERARCHY_USER.userName
     *
     * @return the value of FIN_SALES_HIERARCHY_USER.userName
     *
     * @mbggenerated Thu Dec 12 10:58:31 CST 2013
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_SALES_HIERARCHY_USER.userName
     *
     * @param username the value for FIN_SALES_HIERARCHY_USER.userName
     *
     * @mbggenerated Thu Dec 12 10:58:31 CST 2013
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_SALES_HIERARCHY_USER.MTime
     *
     * @return the value of FIN_SALES_HIERARCHY_USER.MTime
     *
     * @mbggenerated Thu Dec 12 10:58:31 CST 2013
     */
    public Date getMtime() {
        return mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_SALES_HIERARCHY_USER.MTime
     *
     * @param mtime the value for FIN_SALES_HIERARCHY_USER.MTime
     *
     * @mbggenerated Thu Dec 12 10:58:31 CST 2013
     */
    public void setMtime(Date mtime) {
        this.mtime = mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_SALES_HIERARCHY_USER.CTime
     *
     * @return the value of FIN_SALES_HIERARCHY_USER.CTime
     *
     * @mbggenerated Thu Dec 12 10:58:31 CST 2013
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_SALES_HIERARCHY_USER.CTime
     *
     * @param ctime the value for FIN_SALES_HIERARCHY_USER.CTime
     *
     * @mbggenerated Thu Dec 12 10:58:31 CST 2013
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

	public List<FinSalesHierarchyUser> getUnderlingSalersList() {
		return underlingSalersList;
	}

	public void setUnderlingSalersList(List<FinSalesHierarchyUser> underlingSalersList) {
		this.underlingSalersList = underlingSalersList;
	}

	public Long getRelationid() {
		return relationid;
	}

	public void setRelationid(Long relationid) {
		this.relationid = relationid;
	}

}