package com.td.admin.entity;

import java.util.Date;

public class FinSalesHierarchyRelation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_SALES_HIERARCHY_RELATION.id
     *
     * @mbggenerated Thu Dec 12 10:58:31 CST 2013
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_SALES_HIERARCHY_RELATION.groupId
     *
     * @mbggenerated Thu Dec 12 10:58:31 CST 2013
     */
    private Long groupid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_SALES_HIERARCHY_RELATION.userNodeId
     *
     * @mbggenerated Thu Dec 12 10:58:31 CST 2013
     */
    private Long usernodeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_SALES_HIERARCHY_RELATION.code
     *
     * @mbggenerated Thu Dec 12 10:58:31 CST 2013
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_SALES_HIERARCHY_RELATION.MTime
     *
     * @mbggenerated Thu Dec 12 10:58:31 CST 2013
     */
    private Date mtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_SALES_HIERARCHY_RELATION.CTime
     *
     * @mbggenerated Thu Dec 12 10:58:31 CST 2013
     */
    private Date ctime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_SALES_HIERARCHY_RELATION.id
     *
     * @return the value of FIN_SALES_HIERARCHY_RELATION.id
     *
     * @mbggenerated Thu Dec 12 10:58:31 CST 2013
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_SALES_HIERARCHY_RELATION.id
     *
     * @param id the value for FIN_SALES_HIERARCHY_RELATION.id
     *
     * @mbggenerated Thu Dec 12 10:58:31 CST 2013
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_SALES_HIERARCHY_RELATION.groupId
     *
     * @return the value of FIN_SALES_HIERARCHY_RELATION.groupId
     *
     * @mbggenerated Thu Dec 12 10:58:31 CST 2013
     */
    public Long getGroupid() {
        return groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_SALES_HIERARCHY_RELATION.groupId
     *
     * @param groupid the value for FIN_SALES_HIERARCHY_RELATION.groupId
     *
     * @mbggenerated Thu Dec 12 10:58:31 CST 2013
     */
    public void setGroupid(Long groupid) {
        this.groupid = groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_SALES_HIERARCHY_RELATION.userNodeId
     *
     * @return the value of FIN_SALES_HIERARCHY_RELATION.userNodeId
     *
     * @mbggenerated Thu Dec 12 10:58:31 CST 2013
     */
    public Long getUsernodeid() {
        return usernodeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_SALES_HIERARCHY_RELATION.userNodeId
     *
     * @param usernodeid the value for FIN_SALES_HIERARCHY_RELATION.userNodeId
     *
     * @mbggenerated Thu Dec 12 10:58:31 CST 2013
     */
    public void setUsernodeid(Long usernodeid) {
        this.usernodeid = usernodeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_SALES_HIERARCHY_RELATION.code
     *
     * @return the value of FIN_SALES_HIERARCHY_RELATION.code
     *
     * @mbggenerated Thu Dec 12 10:58:31 CST 2013
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_SALES_HIERARCHY_RELATION.code
     *
     * @param code the value for FIN_SALES_HIERARCHY_RELATION.code
     *
     * @mbggenerated Thu Dec 12 10:58:31 CST 2013
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_SALES_HIERARCHY_RELATION.MTime
     *
     * @return the value of FIN_SALES_HIERARCHY_RELATION.MTime
     *
     * @mbggenerated Thu Dec 12 10:58:31 CST 2013
     */
    public Date getMtime() {
        return mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_SALES_HIERARCHY_RELATION.MTime
     *
     * @param mtime the value for FIN_SALES_HIERARCHY_RELATION.MTime
     *
     * @mbggenerated Thu Dec 12 10:58:31 CST 2013
     */
    public void setMtime(Date mtime) {
        this.mtime = mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_SALES_HIERARCHY_RELATION.CTime
     *
     * @return the value of FIN_SALES_HIERARCHY_RELATION.CTime
     *
     * @mbggenerated Thu Dec 12 10:58:31 CST 2013
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_SALES_HIERARCHY_RELATION.CTime
     *
     * @param ctime the value for FIN_SALES_HIERARCHY_RELATION.CTime
     *
     * @mbggenerated Thu Dec 12 10:58:31 CST 2013
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }
}