package com.td.admin.entity;

import java.util.Date;

public class OaSystemregistry {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OA_SYSTEMREGISTRY.id
     *
     * @mbggenerated Mon Aug 19 14:38:07 CST 2013
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OA_SYSTEMREGISTRY.systemKey
     *
     * @mbggenerated Mon Aug 19 14:38:07 CST 2013
     */
    private String systemkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OA_SYSTEMREGISTRY.name
     *
     * @mbggenerated Mon Aug 19 14:38:07 CST 2013
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OA_SYSTEMREGISTRY.accessUrl
     *
     * @mbggenerated Mon Aug 19 14:38:07 CST 2013
     */
    private String accessurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OA_SYSTEMREGISTRY.notifyServiceUrl
     *
     * @mbggenerated Mon Aug 19 14:38:07 CST 2013
     */
    private String notifyserviceurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OA_SYSTEMREGISTRY.serviceType
     *
     * @mbggenerated Mon Aug 19 14:38:07 CST 2013
     */
    private Integer servicetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OA_SYSTEMREGISTRY.MTime
     *
     * @mbggenerated Mon Aug 19 14:38:07 CST 2013
     */
    private Date mtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OA_SYSTEMREGISTRY.CTime
     *
     * @mbggenerated Mon Aug 19 14:38:07 CST 2013
     */
    private Date ctime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OA_SYSTEMREGISTRY.id
     *
     * @return the value of OA_SYSTEMREGISTRY.id
     *
     * @mbggenerated Mon Aug 19 14:38:07 CST 2013
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OA_SYSTEMREGISTRY.id
     *
     * @param id the value for OA_SYSTEMREGISTRY.id
     *
     * @mbggenerated Mon Aug 19 14:38:07 CST 2013
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OA_SYSTEMREGISTRY.systemKey
     *
     * @return the value of OA_SYSTEMREGISTRY.systemKey
     *
     * @mbggenerated Mon Aug 19 14:38:07 CST 2013
     */
    public String getSystemkey() {
        return systemkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OA_SYSTEMREGISTRY.systemKey
     *
     * @param systemkey the value for OA_SYSTEMREGISTRY.systemKey
     *
     * @mbggenerated Mon Aug 19 14:38:07 CST 2013
     */
    public void setSystemkey(String systemkey) {
        this.systemkey = systemkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OA_SYSTEMREGISTRY.name
     *
     * @return the value of OA_SYSTEMREGISTRY.name
     *
     * @mbggenerated Mon Aug 19 14:38:07 CST 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OA_SYSTEMREGISTRY.name
     *
     * @param name the value for OA_SYSTEMREGISTRY.name
     *
     * @mbggenerated Mon Aug 19 14:38:07 CST 2013
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OA_SYSTEMREGISTRY.accessUrl
     *
     * @return the value of OA_SYSTEMREGISTRY.accessUrl
     *
     * @mbggenerated Mon Aug 19 14:38:07 CST 2013
     */
    public String getAccessurl() {
        return accessurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OA_SYSTEMREGISTRY.accessUrl
     *
     * @param accessurl the value for OA_SYSTEMREGISTRY.accessUrl
     *
     * @mbggenerated Mon Aug 19 14:38:07 CST 2013
     */
    public void setAccessurl(String accessurl) {
        this.accessurl = accessurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OA_SYSTEMREGISTRY.notifyServiceUrl
     *
     * @return the value of OA_SYSTEMREGISTRY.notifyServiceUrl
     *
     * @mbggenerated Mon Aug 19 14:38:07 CST 2013
     */
    public String getNotifyserviceurl() {
        return notifyserviceurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OA_SYSTEMREGISTRY.notifyServiceUrl
     *
     * @param notifyserviceurl the value for OA_SYSTEMREGISTRY.notifyServiceUrl
     *
     * @mbggenerated Mon Aug 19 14:38:07 CST 2013
     */
    public void setNotifyserviceurl(String notifyserviceurl) {
        this.notifyserviceurl = notifyserviceurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OA_SYSTEMREGISTRY.serviceType
     *
     * @return the value of OA_SYSTEMREGISTRY.serviceType
     *
     * @mbggenerated Mon Aug 19 14:38:07 CST 2013
     */
    public Integer getServicetype() {
        return servicetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OA_SYSTEMREGISTRY.serviceType
     *
     * @param servicetype the value for OA_SYSTEMREGISTRY.serviceType
     *
     * @mbggenerated Mon Aug 19 14:38:07 CST 2013
     */
    public void setServicetype(Integer servicetype) {
        this.servicetype = servicetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OA_SYSTEMREGISTRY.MTime
     *
     * @return the value of OA_SYSTEMREGISTRY.MTime
     *
     * @mbggenerated Mon Aug 19 14:38:07 CST 2013
     */
    public Date getMtime() {
        return mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OA_SYSTEMREGISTRY.MTime
     *
     * @param mtime the value for OA_SYSTEMREGISTRY.MTime
     *
     * @mbggenerated Mon Aug 19 14:38:07 CST 2013
     */
    public void setMtime(Date mtime) {
        this.mtime = mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OA_SYSTEMREGISTRY.CTime
     *
     * @return the value of OA_SYSTEMREGISTRY.CTime
     *
     * @mbggenerated Mon Aug 19 14:38:07 CST 2013
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OA_SYSTEMREGISTRY.CTime
     *
     * @param ctime the value for OA_SYSTEMREGISTRY.CTime
     *
     * @mbggenerated Mon Aug 19 14:38:07 CST 2013
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }
}