package com.td.admin.entity;

import java.util.Date;

public class SysBusinessSystem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_BUSINESS_SYSTEM.id
     *
     * @mbggenerated Tue Aug 20 09:29:36 CST 2013
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_BUSINESS_SYSTEM.name
     *
     * @mbggenerated Tue Aug 20 09:29:36 CST 2013
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_BUSINESS_SYSTEM.code
     *
     * @mbggenerated Tue Aug 20 09:29:36 CST 2013
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_BUSINESS_SYSTEM.description
     *
     * @mbggenerated Tue Aug 20 09:29:36 CST 2013
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_BUSINESS_SYSTEM.accessUrl
     *
     * @mbggenerated Tue Aug 20 09:29:36 CST 2013
     */
    private String accessurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_BUSINESS_SYSTEM.serverUrl
     *
     * @mbggenerated Tue Aug 20 09:29:36 CST 2013
     */
    private String serverurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_BUSINESS_SYSTEM.MTime
     *
     * @mbggenerated Tue Aug 20 09:29:36 CST 2013
     */
    private Date mtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_BUSINESS_SYSTEM.CTime
     *
     * @mbggenerated Tue Aug 20 09:29:36 CST 2013
     */
    private Date ctime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_BUSINESS_SYSTEM.id
     *
     * @return the value of FIN_BUSINESS_SYSTEM.id
     *
     * @mbggenerated Tue Aug 20 09:29:36 CST 2013
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_BUSINESS_SYSTEM.id
     *
     * @param id the value for FIN_BUSINESS_SYSTEM.id
     *
     * @mbggenerated Tue Aug 20 09:29:36 CST 2013
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_BUSINESS_SYSTEM.name
     *
     * @return the value of FIN_BUSINESS_SYSTEM.name
     *
     * @mbggenerated Tue Aug 20 09:29:36 CST 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_BUSINESS_SYSTEM.name
     *
     * @param name the value for FIN_BUSINESS_SYSTEM.name
     *
     * @mbggenerated Tue Aug 20 09:29:36 CST 2013
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_BUSINESS_SYSTEM.code
     *
     * @return the value of FIN_BUSINESS_SYSTEM.code
     *
     * @mbggenerated Tue Aug 20 09:29:36 CST 2013
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_BUSINESS_SYSTEM.code
     *
     * @param code the value for FIN_BUSINESS_SYSTEM.code
     *
     * @mbggenerated Tue Aug 20 09:29:36 CST 2013
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_BUSINESS_SYSTEM.description
     *
     * @return the value of FIN_BUSINESS_SYSTEM.description
     *
     * @mbggenerated Tue Aug 20 09:29:36 CST 2013
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_BUSINESS_SYSTEM.description
     *
     * @param description the value for FIN_BUSINESS_SYSTEM.description
     *
     * @mbggenerated Tue Aug 20 09:29:36 CST 2013
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_BUSINESS_SYSTEM.accessUrl
     *
     * @return the value of FIN_BUSINESS_SYSTEM.accessUrl
     *
     * @mbggenerated Tue Aug 20 09:29:36 CST 2013
     */
    public String getAccessurl() {
        return accessurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_BUSINESS_SYSTEM.accessUrl
     *
     * @param accessurl the value for FIN_BUSINESS_SYSTEM.accessUrl
     *
     * @mbggenerated Tue Aug 20 09:29:36 CST 2013
     */
    public void setAccessurl(String accessurl) {
        this.accessurl = accessurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_BUSINESS_SYSTEM.serverUrl
     *
     * @return the value of FIN_BUSINESS_SYSTEM.serverUrl
     *
     * @mbggenerated Tue Aug 20 09:29:36 CST 2013
     */
    public String getServerurl() {
        return serverurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_BUSINESS_SYSTEM.serverUrl
     *
     * @param serverurl the value for FIN_BUSINESS_SYSTEM.serverUrl
     *
     * @mbggenerated Tue Aug 20 09:29:36 CST 2013
     */
    public void setServerurl(String serverurl) {
        this.serverurl = serverurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_BUSINESS_SYSTEM.MTime
     *
     * @return the value of FIN_BUSINESS_SYSTEM.MTime
     *
     * @mbggenerated Tue Aug 20 09:29:36 CST 2013
     */
    public Date getMtime() {
        return mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_BUSINESS_SYSTEM.MTime
     *
     * @param mtime the value for FIN_BUSINESS_SYSTEM.MTime
     *
     * @mbggenerated Tue Aug 20 09:29:36 CST 2013
     */
    public void setMtime(Date mtime) {
        this.mtime = mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_BUSINESS_SYSTEM.CTime
     *
     * @return the value of FIN_BUSINESS_SYSTEM.CTime
     *
     * @mbggenerated Tue Aug 20 09:29:36 CST 2013
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_BUSINESS_SYSTEM.CTime
     *
     * @param ctime the value for FIN_BUSINESS_SYSTEM.CTime
     *
     * @mbggenerated Tue Aug 20 09:29:36 CST 2013
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }
}