package com.td.admin.entity;

import java.util.Date;

public class SysCacheInfo {
	private String systemcode;
	private String systemName;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_SYSTEM_CACHEINFO.id
     *
     * @mbggenerated Fri Aug 09 14:44:31 CST 2013
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_SYSTEM_CACHEINFO.cacheName
     *
     * @mbggenerated Fri Aug 09 14:44:31 CST 2013
     */
    private String cachename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_SYSTEM_CACHEINFO.maxEntity
     *
     * @mbggenerated Fri Aug 09 14:44:31 CST 2013
     */
    private Long maxentity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_SYSTEM_CACHEINFO.maxLiveTime
     *
     * @mbggenerated Fri Aug 09 14:44:31 CST 2013
     */
    private Long maxlivetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_SYSTEM_CACHEINFO.description
     *
     * @mbggenerated Fri Aug 09 14:44:31 CST 2013
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_SYSTEM_CACHEINFO.MTime
     *
     * @mbggenerated Fri Aug 09 14:44:31 CST 2013
     */
    private Date mtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_SYSTEM_CACHEINFO.CTime
     *
     * @mbggenerated Fri Aug 09 14:44:31 CST 2013
     */
    private Date ctime;
    
    
  //非数据库字段
    /**
     * 开始记录
     */
    private Long beginIndex;
    
    /**
     * 每页多少
     */
    private Long numPerPage;
    /**
     * 查询页
     */
    private Long pageNum;

    public Long getBeginIndex() {
		return beginIndex;
	}

	public void setBeginIndex(Long beginIndex) {
		this.beginIndex = beginIndex;
	}

	public Long getNumPerPage() {
		return numPerPage;
	}

	public void setNumPerPage(Long numPerPage) {
		this.numPerPage = numPerPage;
	}

	public Long getPageNum() {
		return pageNum;
	}

	public void setPageNum(Long pageNum) {
		this.pageNum = pageNum;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_SYSTEM_CACHEINFO.id
     *
     * @return the value of FIN_SYSTEM_CACHEINFO.id
     *
     * @mbggenerated Fri Aug 09 14:44:31 CST 2013
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_SYSTEM_CACHEINFO.id
     *
     * @param id the value for FIN_SYSTEM_CACHEINFO.id
     *
     * @mbggenerated Fri Aug 09 14:44:31 CST 2013
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_SYSTEM_CACHEINFO.cacheName
     *
     * @return the value of FIN_SYSTEM_CACHEINFO.cacheName
     *
     * @mbggenerated Fri Aug 09 14:44:31 CST 2013
     */
    public String getCachename() {
        return cachename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_SYSTEM_CACHEINFO.cacheName
     *
     * @param cachename the value for FIN_SYSTEM_CACHEINFO.cacheName
     *
     * @mbggenerated Fri Aug 09 14:44:31 CST 2013
     */
    public void setCachename(String cachename) {
        this.cachename = cachename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_SYSTEM_CACHEINFO.maxEntity
     *
     * @return the value of FIN_SYSTEM_CACHEINFO.maxEntity
     *
     * @mbggenerated Fri Aug 09 14:44:31 CST 2013
     */
    public Long getMaxentity() {
        return maxentity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_SYSTEM_CACHEINFO.maxEntity
     *
     * @param maxentity the value for FIN_SYSTEM_CACHEINFO.maxEntity
     *
     * @mbggenerated Fri Aug 09 14:44:31 CST 2013
     */
    public void setMaxentity(Long maxentity) {
        this.maxentity = maxentity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_SYSTEM_CACHEINFO.maxLiveTime
     *
     * @return the value of FIN_SYSTEM_CACHEINFO.maxLiveTime
     *
     * @mbggenerated Fri Aug 09 14:44:31 CST 2013
     */
    public Long getMaxlivetime() {
        return maxlivetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_SYSTEM_CACHEINFO.maxLiveTime
     *
     * @param maxlivetime the value for FIN_SYSTEM_CACHEINFO.maxLiveTime
     *
     * @mbggenerated Fri Aug 09 14:44:31 CST 2013
     */
    public void setMaxlivetime(Long maxlivetime) {
        this.maxlivetime = maxlivetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_SYSTEM_CACHEINFO.description
     *
     * @return the value of FIN_SYSTEM_CACHEINFO.description
     *
     * @mbggenerated Fri Aug 09 14:44:31 CST 2013
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_SYSTEM_CACHEINFO.description
     *
     * @param description the value for FIN_SYSTEM_CACHEINFO.description
     *
     * @mbggenerated Fri Aug 09 14:44:31 CST 2013
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_SYSTEM_CACHEINFO.MTime
     *
     * @return the value of FIN_SYSTEM_CACHEINFO.MTime
     *
     * @mbggenerated Fri Aug 09 14:44:31 CST 2013
     */
    public Date getMtime() {
        return mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_SYSTEM_CACHEINFO.MTime
     *
     * @param mtime the value for FIN_SYSTEM_CACHEINFO.MTime
     *
     * @mbggenerated Fri Aug 09 14:44:31 CST 2013
     */
    public void setMtime(Date mtime) {
        this.mtime = mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_SYSTEM_CACHEINFO.CTime
     *
     * @return the value of FIN_SYSTEM_CACHEINFO.CTime
     *
     * @mbggenerated Fri Aug 09 14:44:31 CST 2013
     */
    public Date getCtime() {
        return ctime;
    }
    

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_SYSTEM_CACHEINFO.CTime
     *
     * @param ctime the value for FIN_SYSTEM_CACHEINFO.CTime
     *
     * @mbggenerated Fri Aug 09 14:44:31 CST 2013
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

	public String getSystemcode() {
		return systemcode;
	}

	public void setSystemcode(String systemcode) {
		this.systemcode = systemcode;
	}

	public String getSystemName() {
		return systemName;
	}

	public void setSystemName(String systemName) {
		this.systemName = systemName;
	}
}