package com.td.admin.entity;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

public class SysDicItem implements Serializable{
	private static final long serialVersionUID = 1L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_DIC_ITEM.id
     *
     * @mbggenerated Fri Aug 09 10:19:21 CST 2013
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_DIC_ITEM.dicItemKey
     *
     * @mbggenerated Fri Aug 09 10:19:21 CST 2013
     */
    private String dicitemkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_DIC_ITEM.dicItemValue
     *
     * @mbggenerated Fri Aug 09 10:19:21 CST 2013
     */
    private String dicitemvalue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_DIC_ITEM.dicId
     *
     * @mbggenerated Fri Aug 09 10:19:21 CST 2013
     */
    private Long dicid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_DIC_ITEM.parentId
     *
     * @mbggenerated Fri Aug 09 10:19:21 CST 2013
     */
    private Long parentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_DIC_ITEM.MTime
     *
     * @mbggenerated Fri Aug 09 10:19:21 CST 2013
     */
    private Date mtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_DIC_ITEM.CTime
     *
     * @mbggenerated Fri Aug 09 10:19:21 CST 2013
     */
    private Date ctime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_DIC_ITEM.id
     *
     * @return the value of FIN_DIC_ITEM.id
     *
     * @mbggenerated Fri Aug 09 10:19:21 CST 2013
     */
    
    private List<SysDicItem> childrenList ; 
    
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_DIC_ITEM.id
     *
     * @param id the value for FIN_DIC_ITEM.id
     *
     * @mbggenerated Fri Aug 09 10:19:21 CST 2013
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_DIC_ITEM.dicItemKey
     *
     * @return the value of FIN_DIC_ITEM.dicItemKey
     *
     * @mbggenerated Fri Aug 09 10:19:21 CST 2013
     */
    public String getDicitemkey() {
        return dicitemkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_DIC_ITEM.dicItemKey
     *
     * @param dicitemkey the value for FIN_DIC_ITEM.dicItemKey
     *
     * @mbggenerated Fri Aug 09 10:19:21 CST 2013
     */
    public void setDicitemkey(String dicitemkey) {
        this.dicitemkey = dicitemkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_DIC_ITEM.dicItemValue
     *
     * @return the value of FIN_DIC_ITEM.dicItemValue
     *
     * @mbggenerated Fri Aug 09 10:19:21 CST 2013
     */
    public String getDicitemvalue() {
        return dicitemvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_DIC_ITEM.dicItemValue
     *
     * @param dicitemvalue the value for FIN_DIC_ITEM.dicItemValue
     *
     * @mbggenerated Fri Aug 09 10:19:21 CST 2013
     */
    public void setDicitemvalue(String dicitemvalue) {
        this.dicitemvalue = dicitemvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_DIC_ITEM.dicId
     *
     * @return the value of FIN_DIC_ITEM.dicId
     *
     * @mbggenerated Fri Aug 09 10:19:21 CST 2013
     */
    public Long getDicid() {
        return dicid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_DIC_ITEM.dicId
     *
     * @param dicid the value for FIN_DIC_ITEM.dicId
     *
     * @mbggenerated Fri Aug 09 10:19:21 CST 2013
     */
    public void setDicid(Long dicid) {
        this.dicid = dicid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_DIC_ITEM.parentId
     *
     * @return the value of FIN_DIC_ITEM.parentId
     *
     * @mbggenerated Fri Aug 09 10:19:21 CST 2013
     */
    public Long getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_DIC_ITEM.parentId
     *
     * @param parentid the value for FIN_DIC_ITEM.parentId
     *
     * @mbggenerated Fri Aug 09 10:19:21 CST 2013
     */
    public void setParentid(Long parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_DIC_ITEM.MTime
     *
     * @return the value of FIN_DIC_ITEM.MTime
     *
     * @mbggenerated Fri Aug 09 10:19:21 CST 2013
     */
    public Date getMtime() {
        return mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_DIC_ITEM.MTime
     *
     * @param mtime the value for FIN_DIC_ITEM.MTime
     *
     * @mbggenerated Fri Aug 09 10:19:21 CST 2013
     */
    public void setMtime(Date mtime) {
        this.mtime = mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_DIC_ITEM.CTime
     *
     * @return the value of FIN_DIC_ITEM.CTime
     *
     * @mbggenerated Fri Aug 09 10:19:21 CST 2013
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_DIC_ITEM.CTime
     *
     * @param ctime the value for FIN_DIC_ITEM.CTime
     *
     * @mbggenerated Fri Aug 09 10:19:21 CST 2013
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

	public List<SysDicItem> getChildrenList() {
		return childrenList;
	}

	public void setChildrenList(List<SysDicItem> childrenList) {
		this.childrenList = childrenList;
	}
}