package com.td.admin.entity;

import java.util.Date;

public class SysEmailTemplate {
	
	private Long beginIndex;
	private Long rows;
	private String systemcode;
	private String systemName;
	private String title;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_EMAIL_TEMPLATE.id
     *
     * @mbggenerated Fri Aug 09 10:57:23 CST 2013
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_EMAIL_TEMPLATE.code
     *
     * @mbggenerated Fri Aug 09 10:57:23 CST 2013
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_EMAIL_TEMPLATE.content
     *
     * @mbggenerated Fri Aug 09 10:57:23 CST 2013
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_EMAIL_TEMPLATE.MTime
     *
     * @mbggenerated Fri Aug 09 10:57:23 CST 2013
     */
    private Date mtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_EMAIL_TEMPLATE.CTime
     *
     * @mbggenerated Fri Aug 09 10:57:23 CST 2013
     */
    private Date ctime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_EMAIL_TEMPLATE.id
     *
     * @return the value of FIN_EMAIL_TEMPLATE.id
     *
     * @mbggenerated Fri Aug 09 10:57:23 CST 2013
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_EMAIL_TEMPLATE.id
     *
     * @param id the value for FIN_EMAIL_TEMPLATE.id
     *
     * @mbggenerated Fri Aug 09 10:57:23 CST 2013
     */
    public void setId(Long id) {
        this.id = id;
    }

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_EMAIL_TEMPLATE.code
     *
     * @return the value of FIN_EMAIL_TEMPLATE.code
     *
     * @mbggenerated Fri Aug 09 10:57:23 CST 2013
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_EMAIL_TEMPLATE.code
     *
     * @param code the value for FIN_EMAIL_TEMPLATE.code
     *
     * @mbggenerated Fri Aug 09 10:57:23 CST 2013
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_EMAIL_TEMPLATE.content
     *
     * @return the value of FIN_EMAIL_TEMPLATE.content
     *
     * @mbggenerated Fri Aug 09 10:57:23 CST 2013
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_EMAIL_TEMPLATE.content
     *
     * @param content the value for FIN_EMAIL_TEMPLATE.content
     *
     * @mbggenerated Fri Aug 09 10:57:23 CST 2013
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_EMAIL_TEMPLATE.MTime
     *
     * @return the value of FIN_EMAIL_TEMPLATE.MTime
     *
     * @mbggenerated Fri Aug 09 10:57:23 CST 2013
     */
    public Date getMtime() {
        return mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_EMAIL_TEMPLATE.MTime
     *
     * @param mtime the value for FIN_EMAIL_TEMPLATE.MTime
     *
     * @mbggenerated Fri Aug 09 10:57:23 CST 2013
     */
    public void setMtime(Date mtime) {
        this.mtime = mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_EMAIL_TEMPLATE.CTime
     *
     * @return the value of FIN_EMAIL_TEMPLATE.CTime
     *
     * @mbggenerated Fri Aug 09 10:57:23 CST 2013
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_EMAIL_TEMPLATE.CTime
     *
     * @param ctime the value for FIN_EMAIL_TEMPLATE.CTime
     *
     * @mbggenerated Fri Aug 09 10:57:23 CST 2013
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

	public Long getBeginIndex() {
		return beginIndex;
	}

	public void setBeginIndex(Long beginIndex) {
		this.beginIndex = beginIndex;
	}

	public Long getRows() {
		return rows;
	}

	public void setRows(Long rows) {
		this.rows = rows;
	}

	public String getSystemcode() {
		return systemcode;
	}

	public void setSystemcode(String systemcode) {
		this.systemcode = systemcode;
	}

	public String getSystemName() {
		return systemName;
	}

	public void setSystemName(String systemName) {
		this.systemName = systemName;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}
}