package com.td.admin.entity;

import java.util.Date;

public class SysEmailSendJobInput {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_EMAIL_SEND_JOB_INPUT.id
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_EMAIL_SEND_JOB_INPUT.emailServerCode
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    private String emailservercode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_EMAIL_SEND_JOB_INPUT.to_
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    private String to;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_EMAIL_SEND_JOB_INPUT.title
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_EMAIL_SEND_JOB_INPUT.content
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_EMAIL_SEND_JOB_INPUT.cc
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    private String cc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_EMAIL_SEND_JOB_INPUT.status
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_EMAIL_SEND_JOB_INPUT.bcc
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    private String bcc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_EMAIL_SEND_JOB_INPUT.retry
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    private Integer retry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_EMAIL_SEND_JOB_INPUT.maxRetry
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    private Integer maxretry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_EMAIL_SEND_JOB_INPUT.createTime
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_EMAIL_SEND_JOB_INPUT.id
     *
     * @return the value of FIN_EMAIL_SEND_JOB_INPUT.id
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_EMAIL_SEND_JOB_INPUT.id
     *
     * @param id the value for FIN_EMAIL_SEND_JOB_INPUT.id
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_EMAIL_SEND_JOB_INPUT.emailServerCode
     *
     * @return the value of FIN_EMAIL_SEND_JOB_INPUT.emailServerCode
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    public String getEmailservercode() {
        return emailservercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_EMAIL_SEND_JOB_INPUT.emailServerCode
     *
     * @param emailservercode the value for FIN_EMAIL_SEND_JOB_INPUT.emailServerCode
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    public void setEmailservercode(String emailservercode) {
        this.emailservercode = emailservercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_EMAIL_SEND_JOB_INPUT.to_
     *
     * @return the value of FIN_EMAIL_SEND_JOB_INPUT.to_
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    public String getTo() {
        return to;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_EMAIL_SEND_JOB_INPUT.to_
     *
     * @param to the value for FIN_EMAIL_SEND_JOB_INPUT.to_
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    public void setTo(String to) {
        this.to = to;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_EMAIL_SEND_JOB_INPUT.title
     *
     * @return the value of FIN_EMAIL_SEND_JOB_INPUT.title
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_EMAIL_SEND_JOB_INPUT.title
     *
     * @param title the value for FIN_EMAIL_SEND_JOB_INPUT.title
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_EMAIL_SEND_JOB_INPUT.content
     *
     * @return the value of FIN_EMAIL_SEND_JOB_INPUT.content
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_EMAIL_SEND_JOB_INPUT.content
     *
     * @param content the value for FIN_EMAIL_SEND_JOB_INPUT.content
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_EMAIL_SEND_JOB_INPUT.cc
     *
     * @return the value of FIN_EMAIL_SEND_JOB_INPUT.cc
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    public String getCc() {
        return cc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_EMAIL_SEND_JOB_INPUT.cc
     *
     * @param cc the value for FIN_EMAIL_SEND_JOB_INPUT.cc
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    public void setCc(String cc) {
        this.cc = cc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_EMAIL_SEND_JOB_INPUT.status
     *
     * @return the value of FIN_EMAIL_SEND_JOB_INPUT.status
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_EMAIL_SEND_JOB_INPUT.status
     *
     * @param status the value for FIN_EMAIL_SEND_JOB_INPUT.status
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_EMAIL_SEND_JOB_INPUT.bcc
     *
     * @return the value of FIN_EMAIL_SEND_JOB_INPUT.bcc
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    public String getBcc() {
        return bcc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_EMAIL_SEND_JOB_INPUT.bcc
     *
     * @param bcc the value for FIN_EMAIL_SEND_JOB_INPUT.bcc
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    public void setBcc(String bcc) {
        this.bcc = bcc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_EMAIL_SEND_JOB_INPUT.retry
     *
     * @return the value of FIN_EMAIL_SEND_JOB_INPUT.retry
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    public Integer getRetry() {
        return retry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_EMAIL_SEND_JOB_INPUT.retry
     *
     * @param retry the value for FIN_EMAIL_SEND_JOB_INPUT.retry
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    public void setRetry(Integer retry) {
        this.retry = retry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_EMAIL_SEND_JOB_INPUT.maxRetry
     *
     * @return the value of FIN_EMAIL_SEND_JOB_INPUT.maxRetry
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    public Integer getMaxretry() {
        return maxretry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_EMAIL_SEND_JOB_INPUT.maxRetry
     *
     * @param maxretry the value for FIN_EMAIL_SEND_JOB_INPUT.maxRetry
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    public void setMaxretry(Integer maxretry) {
        this.maxretry = maxretry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_EMAIL_SEND_JOB_INPUT.createTime
     *
     * @return the value of FIN_EMAIL_SEND_JOB_INPUT.createTime
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_EMAIL_SEND_JOB_INPUT.createTime
     *
     * @param createtime the value for FIN_EMAIL_SEND_JOB_INPUT.createTime
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    
    /**
     * 待发送附件全路径
     */
    private String attachmentPath;
    /**
     * 待发送附件显示名称
     */
    private String attachmentDisplayName;
    
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
    public String getAttachmentPath() {
		return attachmentPath;
	}

	public void setAttachmentPath(String attachmentPath) {
		this.attachmentPath = attachmentPath;
	}
	public String getAttachmentDisplayName() {
		return attachmentDisplayName;
	}

	public void setAttachmentDisplayName(String attachmentDisplayName) {
		this.attachmentDisplayName = attachmentDisplayName;
	}
}