package com.td.admin.entity;

import java.util.Date;

public class SysFtpClientConfig {
	
	private Integer beginIndex;
	
	private Integer numPerPage;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FtpClientConfig.id
     *
     * @mbggenerated Thu Jun 20 17:32:28 CST 2013
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FtpClientConfig.clientName
     *
     * @mbggenerated Thu Jun 20 17:32:28 CST 2013
     */
    private String clientname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FtpClientConfig.rootPath
     *
     * @mbggenerated Thu Jun 20 17:32:28 CST 2013
     */
    private String rootpath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FtpClientConfig.code
     *
     * @mbggenerated Thu Jun 20 17:32:28 CST 2013
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FtpClientConfig.MTime
     *
     * @mbggenerated Thu Jun 20 17:32:28 CST 2013
     */
    private Date mtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FtpClientConfig.CTime
     *
     * @mbggenerated Thu Jun 20 17:32:28 CST 2013
     */
    private Date ctime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FtpClientConfig.id
     *
     * @return the value of FtpClientConfig.id
     *
     * @mbggenerated Thu Jun 20 17:32:28 CST 2013
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FtpClientConfig.id
     *
     * @param id the value for FtpClientConfig.id
     *
     * @mbggenerated Thu Jun 20 17:32:28 CST 2013
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FtpClientConfig.clientName
     *
     * @return the value of FtpClientConfig.clientName
     *
     * @mbggenerated Thu Jun 20 17:32:28 CST 2013
     */
    public String getClientname() {
        return clientname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FtpClientConfig.clientName
     *
     * @param clientname the value for FtpClientConfig.clientName
     *
     * @mbggenerated Thu Jun 20 17:32:28 CST 2013
     */
    public void setClientname(String clientname) {
        this.clientname = clientname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FtpClientConfig.rootPath
     *
     * @return the value of FtpClientConfig.rootPath
     *
     * @mbggenerated Thu Jun 20 17:32:28 CST 2013
     */
    public String getRootpath() {
        return rootpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FtpClientConfig.rootPath
     *
     * @param rootpath the value for FtpClientConfig.rootPath
     *
     * @mbggenerated Thu Jun 20 17:32:28 CST 2013
     */
    public void setRootpath(String rootpath) {
        this.rootpath = rootpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FtpClientConfig.code
     *
     * @return the value of FtpClientConfig.code
     *
     * @mbggenerated Thu Jun 20 17:32:28 CST 2013
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FtpClientConfig.code
     *
     * @param code the value for FtpClientConfig.code
     *
     * @mbggenerated Thu Jun 20 17:32:28 CST 2013
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FtpClientConfig.MTime
     *
     * @return the value of FtpClientConfig.MTime
     *
     * @mbggenerated Thu Jun 20 17:32:28 CST 2013
     */
    public Date getMtime() {
        return mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FtpClientConfig.MTime
     *
     * @param mtime the value for FtpClientConfig.MTime
     *
     * @mbggenerated Thu Jun 20 17:32:28 CST 2013
     */
    public void setMtime(Date mtime) {
        this.mtime = mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FtpClientConfig.CTime
     *
     * @return the value of FtpClientConfig.CTime
     *
     * @mbggenerated Thu Jun 20 17:32:28 CST 2013
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FtpClientConfig.CTime
     *
     * @param ctime the value for FtpClientConfig.CTime
     *
     * @mbggenerated Thu Jun 20 17:32:28 CST 2013
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    public Integer getBeginIndex() {
		return beginIndex;
	}

	public void setBeginIndex(Integer beginIndex) {
		this.beginIndex = beginIndex;
	}

	public Integer getNumPerPage() {
		return numPerPage;
	}

	public void setNumPerPage(Integer numPerPage) {
		this.numPerPage = numPerPage;
	}

	@Override
    public String toString() {
        return "FtpClientConfig [id=" + id + ", clientname=" + clientname + ", rootpath=" + rootpath + ", code=" + code + ", mtime=" + mtime
                + ", ctime=" + ctime + "]";
    }
    
    
}