package com.td.admin.entity;

import java.util.Date;

public class SysFtpServerConfig {
	
	private Integer beginIndex;
	
	private Integer numPerPage;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FtpServerConfig.id
     *
     * @mbggenerated Thu Jun 20 17:32:28 CST 2013
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FtpServerConfig.serverName
     *
     * @mbggenerated Thu Jun 20 17:32:28 CST 2013
     */
    private String servername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FtpServerConfig.protocol
     *
     * @mbggenerated Thu Jun 20 17:32:28 CST 2013
     */
    private String protocol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FtpServerConfig.user
     *
     * @mbggenerated Thu Jun 20 17:32:28 CST 2013
     */
    private String user;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FtpServerConfig.password
     *
     * @mbggenerated Thu Jun 20 17:32:28 CST 2013
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FtpServerConfig.rootPath
     *
     * @mbggenerated Thu Jun 20 17:32:28 CST 2013
     */
    private String rootpath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FtpServerConfig.charset
     *
     * @mbggenerated Thu Jun 20 17:32:28 CST 2013
     */
    private String charset;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FtpServerConfig.host
     *
     * @mbggenerated Thu Jun 20 17:32:28 CST 2013
     */
    private String host;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FtpServerConfig.port
     *
     * @mbggenerated Thu Jun 20 17:32:28 CST 2013
     */
    private Integer port;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FtpServerConfig.code
     *
     * @mbggenerated Thu Jun 20 17:32:28 CST 2013
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FtpServerConfig.MTime
     *
     * @mbggenerated Thu Jun 20 17:32:28 CST 2013
     */
    private Date mtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FtpServerConfig.CTime
     *
     * @mbggenerated Thu Jun 20 17:32:28 CST 2013
     */
    private Date ctime;

    private String oldPassword;

    private String newPassword;
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FtpServerConfig.id
     *
     * @return the value of FtpServerConfig.id
     *
     * @mbggenerated Thu Jun 20 17:32:28 CST 2013
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FtpServerConfig.id
     *
     * @param id the value for FtpServerConfig.id
     *
     * @mbggenerated Thu Jun 20 17:32:28 CST 2013
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FtpServerConfig.serverName
     *
     * @return the value of FtpServerConfig.serverName
     *
     * @mbggenerated Thu Jun 20 17:32:28 CST 2013
     */
    public String getServername() {
        return servername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FtpServerConfig.serverName
     *
     * @param servername the value for FtpServerConfig.serverName
     *
     * @mbggenerated Thu Jun 20 17:32:28 CST 2013
     */
    public void setServername(String servername) {
        this.servername = servername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FtpServerConfig.protocol
     *
     * @return the value of FtpServerConfig.protocol
     *
     * @mbggenerated Thu Jun 20 17:32:28 CST 2013
     */
    public String getProtocol() {
        return protocol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FtpServerConfig.protocol
     *
     * @param protocol the value for FtpServerConfig.protocol
     *
     * @mbggenerated Thu Jun 20 17:32:28 CST 2013
     */
    public void setProtocol(String protocol) {
        this.protocol = protocol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FtpServerConfig.user
     *
     * @return the value of FtpServerConfig.user
     *
     * @mbggenerated Thu Jun 20 17:32:28 CST 2013
     */
    public String getUser() {
        return user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FtpServerConfig.user
     *
     * @param user the value for FtpServerConfig.user
     *
     * @mbggenerated Thu Jun 20 17:32:28 CST 2013
     */
    public void setUser(String user) {
        this.user = user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FtpServerConfig.password
     *
     * @return the value of FtpServerConfig.password
     *
     * @mbggenerated Thu Jun 20 17:32:28 CST 2013
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FtpServerConfig.password
     *
     * @param password the value for FtpServerConfig.password
     *
     * @mbggenerated Thu Jun 20 17:32:28 CST 2013
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FtpServerConfig.rootPath
     *
     * @return the value of FtpServerConfig.rootPath
     *
     * @mbggenerated Thu Jun 20 17:32:28 CST 2013
     */
    public String getRootpath() {
        return rootpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FtpServerConfig.rootPath
     *
     * @param rootpath the value for FtpServerConfig.rootPath
     *
     * @mbggenerated Thu Jun 20 17:32:28 CST 2013
     */
    public void setRootpath(String rootpath) {
        this.rootpath = rootpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FtpServerConfig.charset
     *
     * @return the value of FtpServerConfig.charset
     *
     * @mbggenerated Thu Jun 20 17:32:28 CST 2013
     */
    public String getCharset() {
        return charset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FtpServerConfig.charset
     *
     * @param charset the value for FtpServerConfig.charset
     *
     * @mbggenerated Thu Jun 20 17:32:28 CST 2013
     */
    public void setCharset(String charset) {
        this.charset = charset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FtpServerConfig.host
     *
     * @return the value of FtpServerConfig.host
     *
     * @mbggenerated Thu Jun 20 17:32:28 CST 2013
     */
    public String getHost() {
        return host;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FtpServerConfig.host
     *
     * @param host the value for FtpServerConfig.host
     *
     * @mbggenerated Thu Jun 20 17:32:28 CST 2013
     */
    public void setHost(String host) {
        this.host = host;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FtpServerConfig.port
     *
     * @return the value of FtpServerConfig.port
     *
     * @mbggenerated Thu Jun 20 17:32:28 CST 2013
     */
    public Integer getPort() {
        return port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FtpServerConfig.port
     *
     * @param port the value for FtpServerConfig.port
     *
     * @mbggenerated Thu Jun 20 17:32:28 CST 2013
     */
    public void setPort(Integer port) {
        this.port = port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FtpServerConfig.code
     *
     * @return the value of FtpServerConfig.code
     *
     * @mbggenerated Thu Jun 20 17:32:28 CST 2013
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FtpServerConfig.code
     *
     * @param code the value for FtpServerConfig.code
     *
     * @mbggenerated Thu Jun 20 17:32:28 CST 2013
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FtpServerConfig.MTime
     *
     * @return the value of FtpServerConfig.MTime
     *
     * @mbggenerated Thu Jun 20 17:32:28 CST 2013
     */
    public Date getMtime() {
        return mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FtpServerConfig.MTime
     *
     * @param mtime the value for FtpServerConfig.MTime
     *
     * @mbggenerated Thu Jun 20 17:32:28 CST 2013
     */
    public void setMtime(Date mtime) {
        this.mtime = mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FtpServerConfig.CTime
     *
     * @return the value of FtpServerConfig.CTime
     *
     * @mbggenerated Thu Jun 20 17:32:28 CST 2013
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FtpServerConfig.CTime
     *
     * @param ctime the value for FtpServerConfig.CTime
     *
     * @mbggenerated Thu Jun 20 17:32:28 CST 2013
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }
    
    

    public String getOldPassword() {
        return oldPassword;
    }

    public void setOldPassword(String oldPassword) {
        this.oldPassword = oldPassword;
    }

    public String getNewPassword() {
        return newPassword;
    }

    public void setNewPassword(String newPassword) {
        this.newPassword = newPassword;
    }

    public Integer getBeginIndex() {
		return beginIndex;
	}

	public void setBeginIndex(Integer beginIndex) {
		this.beginIndex = beginIndex;
	}

	public Integer getNumPerPage() {
		return numPerPage;
	}

	public void setNumPerPage(Integer numPerPage) {
		this.numPerPage = numPerPage;
	}

	@Override
    public String toString() {
        return "FtpServerConfig [id=" + id + ", servername=" + servername + ", protocol=" + protocol + ", user=" + user + ", password=" + password
                + ", rootpath=" + rootpath + ", charset=" + charset + ", host=" + host + ", port=" + port + ", code=" + code + ", mtime=" + mtime
                + ", ctime=" + ctime + "]";
    }
    
    
}