package com.td.admin.entity;

import java.util.Date;

public class SysJobConfig {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_JOB_CONFIG.id
     *
     * @mbggenerated Fri Aug 09 14:44:09 CST 2013
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_JOB_CONFIG.name
     *
     * @mbggenerated Fri Aug 09 14:44:09 CST 2013
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_JOB_CONFIG.className
     *
     * @mbggenerated Fri Aug 09 14:44:09 CST 2013
     */
    private String classname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_JOB_CONFIG.intervall
     *
     * @mbggenerated Fri Aug 09 14:44:09 CST 2013
     */
    private String intervall;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_JOB_CONFIG.startTime
     *
     * @mbggenerated Fri Aug 09 14:44:09 CST 2013
     */
    private Date starttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_JOB_CONFIG.endTime
     *
     * @mbggenerated Fri Aug 09 14:44:09 CST 2013
     */
    private Date endtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_JOB_CONFIG.repeatTime
     *
     * @mbggenerated Fri Aug 09 14:44:09 CST 2013
     */
    private Integer repeattime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_JOB_CONFIG.executeTime
     *
     * @mbggenerated Fri Aug 09 14:44:09 CST 2013
     */
    private Integer executetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_JOB_CONFIG.status
     *
     * @mbggenerated Fri Aug 09 14:44:09 CST 2013
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_JOB_CONFIG.jkey
     *
     * @mbggenerated Fri Aug 09 14:44:09 CST 2013
     */
    private String jkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_JOB_CONFIG.MTime
     *
     * @mbggenerated Fri Aug 09 14:44:09 CST 2013
     */
    private Date mtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_JOB_CONFIG.CTime
     *
     * @mbggenerated Fri Aug 09 14:44:09 CST 2013
     */
    private Date ctime;
    
    
    private String systemcode ; 
    
    private String sysname; 
    
    
    
	public String getSysname() {
		return sysname;
	}

	public void setSysname(String sysname) {
		this.sysname = sysname;
	}

	public String getSystemcode() {
		return systemcode;
	}

	public void setSystemcode(String systemcode) {
		this.systemcode = systemcode;
	}

	//非数据库字段
    /**
     * 开始记录
     */
    private Long beginIndex;
    
	/**
     * 每页多少
     */
    private Long numPerPage;
    /**
     * 查询页
     */
    private Long pageNum;

    public Long getBeginIndex() {
		return beginIndex;
	}

	public void setBeginIndex(Long beginIndex) {
		this.beginIndex = beginIndex;
	}

	public Long getNumPerPage() {
		return numPerPage;
	}

	public void setNumPerPage(Long numPerPage) {
		this.numPerPage = numPerPage;
	}

	public Long getPageNum() {
		return pageNum;
	}

	public void setPageNum(Long pageNum) {
		this.pageNum = pageNum;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_JOB_CONFIG.id
     *
     * @return the value of FIN_JOB_CONFIG.id
     *
     * @mbggenerated Fri Aug 09 14:44:09 CST 2013
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_JOB_CONFIG.id
     *
     * @param id the value for FIN_JOB_CONFIG.id
     *
     * @mbggenerated Fri Aug 09 14:44:09 CST 2013
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_JOB_CONFIG.name
     *
     * @return the value of FIN_JOB_CONFIG.name
     *
     * @mbggenerated Fri Aug 09 14:44:09 CST 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_JOB_CONFIG.name
     *
     * @param name the value for FIN_JOB_CONFIG.name
     *
     * @mbggenerated Fri Aug 09 14:44:09 CST 2013
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_JOB_CONFIG.className
     *
     * @return the value of FIN_JOB_CONFIG.className
     *
     * @mbggenerated Fri Aug 09 14:44:09 CST 2013
     */
    public String getClassname() {
        return classname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_JOB_CONFIG.className
     *
     * @param classname the value for FIN_JOB_CONFIG.className
     *
     * @mbggenerated Fri Aug 09 14:44:09 CST 2013
     */
    public void setClassname(String classname) {
        this.classname = classname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_JOB_CONFIG.intervall
     *
     * @return the value of FIN_JOB_CONFIG.intervall
     *
     * @mbggenerated Fri Aug 09 14:44:09 CST 2013
     */
    public String getIntervall() {
        return intervall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_JOB_CONFIG.intervall
     *
     * @param intervall the value for FIN_JOB_CONFIG.intervall
     *
     * @mbggenerated Fri Aug 09 14:44:09 CST 2013
     */
    public void setIntervall(String intervall) {
        this.intervall = intervall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_JOB_CONFIG.startTime
     *
     * @return the value of FIN_JOB_CONFIG.startTime
     *
     * @mbggenerated Fri Aug 09 14:44:09 CST 2013
     */
    public Date getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_JOB_CONFIG.startTime
     *
     * @param starttime the value for FIN_JOB_CONFIG.startTime
     *
     * @mbggenerated Fri Aug 09 14:44:09 CST 2013
     */
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_JOB_CONFIG.endTime
     *
     * @return the value of FIN_JOB_CONFIG.endTime
     *
     * @mbggenerated Fri Aug 09 14:44:09 CST 2013
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_JOB_CONFIG.endTime
     *
     * @param endtime the value for FIN_JOB_CONFIG.endTime
     *
     * @mbggenerated Fri Aug 09 14:44:09 CST 2013
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_JOB_CONFIG.repeatTime
     *
     * @return the value of FIN_JOB_CONFIG.repeatTime
     *
     * @mbggenerated Fri Aug 09 14:44:09 CST 2013
     */
    public Integer getRepeattime() {
        return repeattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_JOB_CONFIG.repeatTime
     *
     * @param repeattime the value for FIN_JOB_CONFIG.repeatTime
     *
     * @mbggenerated Fri Aug 09 14:44:09 CST 2013
     */
    public void setRepeattime(Integer repeattime) {
        this.repeattime = repeattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_JOB_CONFIG.executeTime
     *
     * @return the value of FIN_JOB_CONFIG.executeTime
     *
     * @mbggenerated Fri Aug 09 14:44:09 CST 2013
     */
    public Integer getExecutetime() {
        return executetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_JOB_CONFIG.executeTime
     *
     * @param executetime the value for FIN_JOB_CONFIG.executeTime
     *
     * @mbggenerated Fri Aug 09 14:44:09 CST 2013
     */
    public void setExecutetime(Integer executetime) {
        this.executetime = executetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_JOB_CONFIG.status
     *
     * @return the value of FIN_JOB_CONFIG.status
     *
     * @mbggenerated Fri Aug 09 14:44:09 CST 2013
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_JOB_CONFIG.status
     *
     * @param status the value for FIN_JOB_CONFIG.status
     *
     * @mbggenerated Fri Aug 09 14:44:09 CST 2013
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_JOB_CONFIG.jkey
     *
     * @return the value of FIN_JOB_CONFIG.jkey
     *
     * @mbggenerated Fri Aug 09 14:44:09 CST 2013
     */
    public String getJkey() {
        return jkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_JOB_CONFIG.jkey
     *
     * @param jkey the value for FIN_JOB_CONFIG.jkey
     *
     * @mbggenerated Fri Aug 09 14:44:09 CST 2013
     */
    public void setJkey(String jkey) {
        this.jkey = jkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_JOB_CONFIG.MTime
     *
     * @return the value of FIN_JOB_CONFIG.MTime
     *
     * @mbggenerated Fri Aug 09 14:44:09 CST 2013
     */
    public Date getMtime() {
        return mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_JOB_CONFIG.MTime
     *
     * @param mtime the value for FIN_JOB_CONFIG.MTime
     *
     * @mbggenerated Fri Aug 09 14:44:09 CST 2013
     */
    public void setMtime(Date mtime) {
        this.mtime = mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_JOB_CONFIG.CTime
     *
     * @return the value of FIN_JOB_CONFIG.CTime
     *
     * @mbggenerated Fri Aug 09 14:44:09 CST 2013
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_JOB_CONFIG.CTime
     *
     * @param ctime the value for FIN_JOB_CONFIG.CTime
     *
     * @mbggenerated Fri Aug 09 14:44:09 CST 2013
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_JOB_CONFIG.triggerType
     *
     * @mbggenerated Sat Dec 28 12:47:31 CST 2013
     */
    private String triggertype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_JOB_CONFIG.cronExpression
     *
     * @mbggenerated Sat Dec 28 16:04:02 CST 2013
     */
    private String cronexpression;

	public String getTriggertype() {
		return triggertype;
	}

	public void setTriggertype(String triggertype) {
		this.triggertype = triggertype;
	}

	public String getCronexpression() {
		return cronexpression;
	}

	public void setCronexpression(String cronexpression) {
		this.cronexpression = cronexpression;
	}


    
    
    
    
}