package com.td.admin.entity;

import java.util.Date;

public class SysJobTempJobInput {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_JOB_TEMPJOBINPUT.id
     *
     * @mbggenerated Fri Aug 09 14:39:11 CST 2013
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_JOB_TEMPJOBINPUT.executorClassName
     *
     * @mbggenerated Fri Aug 09 14:39:11 CST 2013
     */
    private String executorclassname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_JOB_TEMPJOBINPUT.startTime
     *
     * @mbggenerated Fri Aug 09 14:39:11 CST 2013
     */
    private Date starttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_JOB_TEMPJOBINPUT.repeatTime
     *
     * @mbggenerated Fri Aug 09 14:39:11 CST 2013
     */
    private Integer repeattime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_JOB_TEMPJOBINPUT.executeTime
     *
     * @mbggenerated Fri Aug 09 14:39:11 CST 2013
     */
    private Integer executetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_JOB_TEMPJOBINPUT.status
     *
     * @mbggenerated Fri Aug 09 14:39:11 CST 2013
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_JOB_TEMPJOBINPUT.param
     *
     * @mbggenerated Fri Aug 09 14:39:11 CST 2013
     */
    private String param;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_JOB_TEMPJOBINPUT.MTime
     *
     * @mbggenerated Fri Aug 09 14:39:11 CST 2013
     */
    private Date mtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_JOB_TEMPJOBINPUT.CTime
     *
     * @mbggenerated Fri Aug 09 14:39:11 CST 2013
     */
    private Date ctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_JOB_TEMPJOBINPUT.jkey
     *
     * @mbggenerated Fri Aug 09 14:39:11 CST 2013
     */
    private String jkey;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_JOB_TEMPJOBINPUT.id
     *
     * @return the value of FIN_JOB_TEMPJOBINPUT.id
     *
     * @mbggenerated Fri Aug 09 14:39:11 CST 2013
     */
    
    
    //非数据库字段
    /**
     * 开始记录
     */
    private Long beginIndex;
    
    /**
     * 每页多少
     */
    private Long numPerPage;
    /**
     * 查询页
     */
    private Long pageNum;
    
  //查询条件
    private Date fromStarttime;
    
    private Date toStarttime;
    

    
	public Date getFromStarttime() {
		return fromStarttime;
	}

	public void setFromStarttime(Date fromStarttime) {
		this.fromStarttime = fromStarttime;
	}

	public Date getToStarttime() {
		return toStarttime;
	}

	public void setToStarttime(Date toStarttime) {
		this.toStarttime = toStarttime;
	}

	public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_JOB_TEMPJOBINPUT.id
     *
     * @param id the value for FIN_JOB_TEMPJOBINPUT.id
     *
     * @mbggenerated Fri Aug 09 14:39:11 CST 2013
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_JOB_TEMPJOBINPUT.executorClassName
     *
     * @return the value of FIN_JOB_TEMPJOBINPUT.executorClassName
     *
     * @mbggenerated Fri Aug 09 14:39:11 CST 2013
     */
    public String getExecutorclassname() {
        return executorclassname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_JOB_TEMPJOBINPUT.executorClassName
     *
     * @param executorclassname the value for FIN_JOB_TEMPJOBINPUT.executorClassName
     *
     * @mbggenerated Fri Aug 09 14:39:11 CST 2013
     */
    public void setExecutorclassname(String executorclassname) {
        this.executorclassname = executorclassname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_JOB_TEMPJOBINPUT.startTime
     *
     * @return the value of FIN_JOB_TEMPJOBINPUT.startTime
     *
     * @mbggenerated Fri Aug 09 14:39:11 CST 2013
     */
    public Date getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_JOB_TEMPJOBINPUT.startTime
     *
     * @param starttime the value for FIN_JOB_TEMPJOBINPUT.startTime
     *
     * @mbggenerated Fri Aug 09 14:39:11 CST 2013
     */
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_JOB_TEMPJOBINPUT.repeatTime
     *
     * @return the value of FIN_JOB_TEMPJOBINPUT.repeatTime
     *
     * @mbggenerated Fri Aug 09 14:39:11 CST 2013
     */
    public Integer getRepeattime() {
        return repeattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_JOB_TEMPJOBINPUT.repeatTime
     *
     * @param repeattime the value for FIN_JOB_TEMPJOBINPUT.repeatTime
     *
     * @mbggenerated Fri Aug 09 14:39:11 CST 2013
     */
    public void setRepeattime(Integer repeattime) {
        this.repeattime = repeattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_JOB_TEMPJOBINPUT.executeTime
     *
     * @return the value of FIN_JOB_TEMPJOBINPUT.executeTime
     *
     * @mbggenerated Fri Aug 09 14:39:11 CST 2013
     */
    public Integer getExecutetime() {
        return executetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_JOB_TEMPJOBINPUT.executeTime
     *
     * @param executetime the value for FIN_JOB_TEMPJOBINPUT.executeTime
     *
     * @mbggenerated Fri Aug 09 14:39:11 CST 2013
     */
    public void setExecutetime(Integer executetime) {
        this.executetime = executetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_JOB_TEMPJOBINPUT.status
     *
     * @return the value of FIN_JOB_TEMPJOBINPUT.status
     *
     * @mbggenerated Fri Aug 09 14:39:11 CST 2013
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_JOB_TEMPJOBINPUT.status
     *
     * @param status the value for FIN_JOB_TEMPJOBINPUT.status
     *
     * @mbggenerated Fri Aug 09 14:39:11 CST 2013
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_JOB_TEMPJOBINPUT.param
     *
     * @return the value of FIN_JOB_TEMPJOBINPUT.param
     *
     * @mbggenerated Fri Aug 09 14:39:11 CST 2013
     */
    public String getParam() {
        return param;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_JOB_TEMPJOBINPUT.param
     *
     * @param param the value for FIN_JOB_TEMPJOBINPUT.param
     *
     * @mbggenerated Fri Aug 09 14:39:11 CST 2013
     */
    public void setParam(String param) {
        this.param = param;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_JOB_TEMPJOBINPUT.MTime
     *
     * @return the value of FIN_JOB_TEMPJOBINPUT.MTime
     *
     * @mbggenerated Fri Aug 09 14:39:11 CST 2013
     */
    public Date getMtime() {
        return mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_JOB_TEMPJOBINPUT.MTime
     *
     * @param mtime the value for FIN_JOB_TEMPJOBINPUT.MTime
     *
     * @mbggenerated Fri Aug 09 14:39:11 CST 2013
     */
    public void setMtime(Date mtime) {
        this.mtime = mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_JOB_TEMPJOBINPUT.CTime
     *
     * @return the value of FIN_JOB_TEMPJOBINPUT.CTime
     *
     * @mbggenerated Fri Aug 09 14:39:11 CST 2013
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_JOB_TEMPJOBINPUT.CTime
     *
     * @param ctime the value for FIN_JOB_TEMPJOBINPUT.CTime
     *
     * @mbggenerated Fri Aug 09 14:39:11 CST 2013
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_JOB_TEMPJOBINPUT.jkey
     *
     * @return the value of FIN_JOB_TEMPJOBINPUT.jkey
     *
     * @mbggenerated Fri Aug 09 14:39:11 CST 2013
     */
    public String getJkey() {
        return jkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_JOB_TEMPJOBINPUT.jkey
     *
     * @param jkey the value for FIN_JOB_TEMPJOBINPUT.jkey
     *
     * @mbggenerated Fri Aug 09 14:39:11 CST 2013
     */
    public void setJkey(String jkey) {
        this.jkey = jkey;
    }
    
    public Long getBeginIndex() {
		return beginIndex;
	}

	public void setBeginIndex(Long beginIndex) {
		this.beginIndex = beginIndex;
	}

	public Long getNumPerPage() {
		return numPerPage;
	}

	public void setNumPerPage(Long numPerPage) {
		this.numPerPage = numPerPage;
	}

	public Long getPageNum() {
		return pageNum;
	}

	public void setPageNum(Long pageNum) {
		this.pageNum = pageNum;
	}

}