package com.td.admin.entity;

import java.util.Date;

public class SysOaInstance {
	private Integer beginIndex;
	private Integer numPerPage;
	private String fatherPIName; 
	private String templateName;
	private String statusName;
	private Date findStartTime;
	private Date findEndTime;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OA_OAINSTANCE.id
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OA_OAINSTANCE.templateCode
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    private String templatecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OA_OAINSTANCE.activitiProcessInstanceId
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    private String activitiprocessinstanceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OA_OAINSTANCE.fatherProcessInstnaceId
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    private Long fatherprocessinstnaceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OA_OAINSTANCE.templateType
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    private Integer templatetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OA_OAINSTANCE.startTime
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    private Date starttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OA_OAINSTANCE.starterUmId
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    private String starterumid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OA_OAINSTANCE.starterName
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    private String startername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OA_OAINSTANCE.title
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OA_OAINSTANCE.content
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OA_OAINSTANCE.endTime
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    private Date endtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OA_OAINSTANCE.status
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OA_OAINSTANCE.MTime
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    private Date mtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OA_OAINSTANCE.CTime
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    private Date ctime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OA_OAINSTANCE.id
     *
     * @return the value of OA_OAINSTANCE.id
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OA_OAINSTANCE.id
     *
     * @param id the value for OA_OAINSTANCE.id
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OA_OAINSTANCE.templateCode
     *
     * @return the value of OA_OAINSTANCE.templateCode
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    public String getTemplatecode() {
        return templatecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OA_OAINSTANCE.templateCode
     *
     * @param templatecode the value for OA_OAINSTANCE.templateCode
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    public void setTemplatecode(String templatecode) {
        this.templatecode = templatecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OA_OAINSTANCE.activitiProcessInstanceId
     *
     * @return the value of OA_OAINSTANCE.activitiProcessInstanceId
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    public String getActivitiprocessinstanceid() {
        return activitiprocessinstanceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OA_OAINSTANCE.activitiProcessInstanceId
     *
     * @param activitiprocessinstanceid the value for OA_OAINSTANCE.activitiProcessInstanceId
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    public void setActivitiprocessinstanceid(String activitiprocessinstanceid) {
        this.activitiprocessinstanceid = activitiprocessinstanceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OA_OAINSTANCE.fatherProcessInstnaceId
     *
     * @return the value of OA_OAINSTANCE.fatherProcessInstnaceId
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    public Long getFatherprocessinstnaceid() {
        return fatherprocessinstnaceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OA_OAINSTANCE.fatherProcessInstnaceId
     *
     * @param fatherprocessinstnaceid the value for OA_OAINSTANCE.fatherProcessInstnaceId
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    public void setFatherprocessinstnaceid(Long fatherprocessinstnaceid) {
        this.fatherprocessinstnaceid = fatherprocessinstnaceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OA_OAINSTANCE.templateType
     *
     * @return the value of OA_OAINSTANCE.templateType
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    public Integer getTemplatetype() {
        return templatetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OA_OAINSTANCE.templateType
     *
     * @param templatetype the value for OA_OAINSTANCE.templateType
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    public void setTemplatetype(Integer templatetype) {
        this.templatetype = templatetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OA_OAINSTANCE.startTime
     *
     * @return the value of OA_OAINSTANCE.startTime
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    public Date getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OA_OAINSTANCE.startTime
     *
     * @param starttime the value for OA_OAINSTANCE.startTime
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OA_OAINSTANCE.starterUmId
     *
     * @return the value of OA_OAINSTANCE.starterUmId
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    public String getStarterumid() {
        return starterumid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OA_OAINSTANCE.starterUmId
     *
     * @param starterumid the value for OA_OAINSTANCE.starterUmId
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    public void setStarterumid(String starterumid) {
        this.starterumid = starterumid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OA_OAINSTANCE.starterName
     *
     * @return the value of OA_OAINSTANCE.starterName
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    public String getStartername() {
        return startername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OA_OAINSTANCE.starterName
     *
     * @param startername the value for OA_OAINSTANCE.starterName
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    public void setStartername(String startername) {
        this.startername = startername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OA_OAINSTANCE.title
     *
     * @return the value of OA_OAINSTANCE.title
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OA_OAINSTANCE.title
     *
     * @param title the value for OA_OAINSTANCE.title
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OA_OAINSTANCE.content
     *
     * @return the value of OA_OAINSTANCE.content
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OA_OAINSTANCE.content
     *
     * @param content the value for OA_OAINSTANCE.content
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OA_OAINSTANCE.endTime
     *
     * @return the value of OA_OAINSTANCE.endTime
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OA_OAINSTANCE.endTime
     *
     * @param endtime the value for OA_OAINSTANCE.endTime
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OA_OAINSTANCE.status
     *
     * @return the value of OA_OAINSTANCE.status
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OA_OAINSTANCE.status
     *
     * @param status the value for OA_OAINSTANCE.status
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OA_OAINSTANCE.MTime
     *
     * @return the value of OA_OAINSTANCE.MTime
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    public Date getMtime() {
        return mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OA_OAINSTANCE.MTime
     *
     * @param mtime the value for OA_OAINSTANCE.MTime
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    public void setMtime(Date mtime) {
        this.mtime = mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OA_OAINSTANCE.CTime
     *
     * @return the value of OA_OAINSTANCE.CTime
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OA_OAINSTANCE.CTime
     *
     * @param ctime the value for OA_OAINSTANCE.CTime
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

	public Integer getBeginIndex() {
		return beginIndex;
	}

	public void setBeginIndex(Integer beginIndex) {
		this.beginIndex = beginIndex;
	}

	public Integer getNumPerPage() {
		return numPerPage;
	}

	public void setNumPerPage(Integer numPerPage) {
		this.numPerPage = numPerPage;
	}

	public String getFatherPIName() {
		return fatherPIName;
	}

	public void setFatherPIName(String fatherPIName) {
		this.fatherPIName = fatherPIName;
	}

	public String getTemplateName() {
		return templateName;
	}

	public void setTemplateName(String templateName) {
		this.templateName = templateName;
	}

	public String getStatusName() {
		return statusName;
	}

	public void setStatusName(String statusName) {
		this.statusName = statusName;
	}

	public Date getFindStartTime() {
		return findStartTime;
	}

	public void setFindStartTime(Date findStartTime) {
		this.findStartTime = findStartTime;
	}

	public Date getFindEndTime() {
		return findEndTime;
	}

	public void setFindEndTime(Date findEndTime) {
		this.findEndTime = findEndTime;
	}
}