package com.td.admin.entity;

import java.util.Date;

public class SysOaTemplateTask {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OA_TEMPLATETASK.id
     *
     * @mbggenerated Wed Aug 28 11:37:25 CST 2013
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OA_TEMPLATETASK.taskName
     *
     * @mbggenerated Wed Aug 28 11:37:25 CST 2013
     */
    private String taskname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OA_TEMPLATETASK.taskIndex
     *
     * @mbggenerated Wed Aug 28 11:37:25 CST 2013
     */
    private Integer taskindex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OA_TEMPLATETASK.templateId
     *
     * @mbggenerated Wed Aug 28 11:37:25 CST 2013
     */
    private Long templateid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OA_TEMPLATETASK.taskDescription
     *
     * @mbggenerated Wed Aug 28 11:37:25 CST 2013
     */
    private String taskdescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OA_TEMPLATETASK.approverUmId
     *
     * @mbggenerated Wed Aug 28 11:37:25 CST 2013
     */
    private String approverumid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OA_TEMPLATETASK.approverName
     *
     * @mbggenerated Wed Aug 28 11:37:25 CST 2013
     */
    private String approvername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OA_TEMPLATETASK.taskStartEmailTemplateId
     *
     * @mbggenerated Wed Aug 28 11:37:25 CST 2013
     */
    private Long taskstartemailtemplateid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OA_TEMPLATETASK.taskeEndEmailTemplateId
     *
     * @mbggenerated Wed Aug 28 11:37:25 CST 2013
     */
    private Long taskeendemailtemplateid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OA_TEMPLATETASK.taskCode
     *
     * @mbggenerated Wed Aug 28 11:37:25 CST 2013
     */
    private String taskcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OA_TEMPLATETASK.MTime
     *
     * @mbggenerated Wed Aug 28 11:37:25 CST 2013
     */
    private Date mtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OA_TEMPLATETASK.CTime
     *
     * @mbggenerated Wed Aug 28 11:37:25 CST 2013
     */
    private Date ctime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OA_TEMPLATETASK.id
     *
     * @return the value of OA_TEMPLATETASK.id
     *
     * @mbggenerated Wed Aug 28 11:37:25 CST 2013
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OA_TEMPLATETASK.id
     *
     * @param id the value for OA_TEMPLATETASK.id
     *
     * @mbggenerated Wed Aug 28 11:37:25 CST 2013
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OA_TEMPLATETASK.taskName
     *
     * @return the value of OA_TEMPLATETASK.taskName
     *
     * @mbggenerated Wed Aug 28 11:37:25 CST 2013
     */
    public String getTaskname() {
        return taskname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OA_TEMPLATETASK.taskName
     *
     * @param taskname the value for OA_TEMPLATETASK.taskName
     *
     * @mbggenerated Wed Aug 28 11:37:25 CST 2013
     */
    public void setTaskname(String taskname) {
        this.taskname = taskname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OA_TEMPLATETASK.taskIndex
     *
     * @return the value of OA_TEMPLATETASK.taskIndex
     *
     * @mbggenerated Wed Aug 28 11:37:25 CST 2013
     */
    public Integer getTaskindex() {
        return taskindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OA_TEMPLATETASK.taskIndex
     *
     * @param taskindex the value for OA_TEMPLATETASK.taskIndex
     *
     * @mbggenerated Wed Aug 28 11:37:25 CST 2013
     */
    public void setTaskindex(Integer taskindex) {
        this.taskindex = taskindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OA_TEMPLATETASK.templateId
     *
     * @return the value of OA_TEMPLATETASK.templateId
     *
     * @mbggenerated Wed Aug 28 11:37:25 CST 2013
     */
    public Long getTemplateid() {
        return templateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OA_TEMPLATETASK.templateId
     *
     * @param templateid the value for OA_TEMPLATETASK.templateId
     *
     * @mbggenerated Wed Aug 28 11:37:25 CST 2013
     */
    public void setTemplateid(Long templateid) {
        this.templateid = templateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OA_TEMPLATETASK.taskDescription
     *
     * @return the value of OA_TEMPLATETASK.taskDescription
     *
     * @mbggenerated Wed Aug 28 11:37:25 CST 2013
     */
    public String getTaskdescription() {
        return taskdescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OA_TEMPLATETASK.taskDescription
     *
     * @param taskdescription the value for OA_TEMPLATETASK.taskDescription
     *
     * @mbggenerated Wed Aug 28 11:37:25 CST 2013
     */
    public void setTaskdescription(String taskdescription) {
        this.taskdescription = taskdescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OA_TEMPLATETASK.approverUmId
     *
     * @return the value of OA_TEMPLATETASK.approverUmId
     *
     * @mbggenerated Wed Aug 28 11:37:25 CST 2013
     */
    public String getApproverumid() {
        return approverumid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OA_TEMPLATETASK.approverUmId
     *
     * @param approverumid the value for OA_TEMPLATETASK.approverUmId
     *
     * @mbggenerated Wed Aug 28 11:37:25 CST 2013
     */
    public void setApproverumid(String approverumid) {
        this.approverumid = approverumid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OA_TEMPLATETASK.approverName
     *
     * @return the value of OA_TEMPLATETASK.approverName
     *
     * @mbggenerated Wed Aug 28 11:37:25 CST 2013
     */
    public String getApprovername() {
        return approvername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OA_TEMPLATETASK.approverName
     *
     * @param approvername the value for OA_TEMPLATETASK.approverName
     *
     * @mbggenerated Wed Aug 28 11:37:25 CST 2013
     */
    public void setApprovername(String approvername) {
        this.approvername = approvername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OA_TEMPLATETASK.taskStartEmailTemplateId
     *
     * @return the value of OA_TEMPLATETASK.taskStartEmailTemplateId
     *
     * @mbggenerated Wed Aug 28 11:37:25 CST 2013
     */
    public Long getTaskstartemailtemplateid() {
        return taskstartemailtemplateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OA_TEMPLATETASK.taskStartEmailTemplateId
     *
     * @param taskstartemailtemplateid the value for OA_TEMPLATETASK.taskStartEmailTemplateId
     *
     * @mbggenerated Wed Aug 28 11:37:25 CST 2013
     */
    public void setTaskstartemailtemplateid(Long taskstartemailtemplateid) {
        this.taskstartemailtemplateid = taskstartemailtemplateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OA_TEMPLATETASK.taskeEndEmailTemplateId
     *
     * @return the value of OA_TEMPLATETASK.taskeEndEmailTemplateId
     *
     * @mbggenerated Wed Aug 28 11:37:25 CST 2013
     */
    public Long getTaskeendemailtemplateid() {
        return taskeendemailtemplateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OA_TEMPLATETASK.taskeEndEmailTemplateId
     *
     * @param taskeendemailtemplateid the value for OA_TEMPLATETASK.taskeEndEmailTemplateId
     *
     * @mbggenerated Wed Aug 28 11:37:25 CST 2013
     */
    public void setTaskeendemailtemplateid(Long taskeendemailtemplateid) {
        this.taskeendemailtemplateid = taskeendemailtemplateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OA_TEMPLATETASK.taskCode
     *
     * @return the value of OA_TEMPLATETASK.taskCode
     *
     * @mbggenerated Wed Aug 28 11:37:25 CST 2013
     */
    public String getTaskcode() {
        return taskcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OA_TEMPLATETASK.taskCode
     *
     * @param taskcode the value for OA_TEMPLATETASK.taskCode
     *
     * @mbggenerated Wed Aug 28 11:37:25 CST 2013
     */
    public void setTaskcode(String taskcode) {
        this.taskcode = taskcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OA_TEMPLATETASK.MTime
     *
     * @return the value of OA_TEMPLATETASK.MTime
     *
     * @mbggenerated Wed Aug 28 11:37:25 CST 2013
     */
    public Date getMtime() {
        return mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OA_TEMPLATETASK.MTime
     *
     * @param mtime the value for OA_TEMPLATETASK.MTime
     *
     * @mbggenerated Wed Aug 28 11:37:25 CST 2013
     */
    public void setMtime(Date mtime) {
        this.mtime = mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OA_TEMPLATETASK.CTime
     *
     * @return the value of OA_TEMPLATETASK.CTime
     *
     * @mbggenerated Wed Aug 28 11:37:25 CST 2013
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OA_TEMPLATETASK.CTime
     *
     * @param ctime the value for OA_TEMPLATETASK.CTime
     *
     * @mbggenerated Wed Aug 28 11:37:25 CST 2013
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }
}