package com.td.admin.entity;

import java.io.Serializable;
import java.util.Date;
import java.util.List;


public class SysOaTemplate implements Serializable{
	private static final long serialVersionUID = 1L;
	 private String systemcode;
	 private String systemName;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OA_OATEMPLATE.id
     *
     * @mbggenerated Mon Aug 19 14:32:48 CST 2013
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OA_OATEMPLATE.code
     *
     * @mbggenerated Mon Aug 19 14:32:48 CST 2013
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OA_OATEMPLATE.name
     *
     * @mbggenerated Mon Aug 19 14:32:48 CST 2013
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OA_OATEMPLATE.description
     *
     * @mbggenerated Mon Aug 19 14:32:48 CST 2013
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OA_OATEMPLATE.status
     *
     * @mbggenerated Mon Aug 19 14:32:48 CST 2013
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OA_OATEMPLATE.MTime
     *
     * @mbggenerated Mon Aug 19 14:32:48 CST 2013
     */
    private Date mtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OA_OATEMPLATE.CTime
     *
     * @mbggenerated Mon Aug 19 14:32:48 CST 2013
     */
    private Date ctime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OA_OATEMPLATE.id
     *
     * @return the value of OA_OATEMPLATE.id
     *
     * @mbggenerated Mon Aug 19 14:32:48 CST 2013
     *
     */
    
    /**
     * 非数据库字段
     */
    private Long pageNum;
    
    private Long beginIndex;

	private Long numPerPage; 

	
	/**
	 * 审批链
	 */
	private List<SysOaTemplateTask> oaTemplatetasks;

	/**
	 * 接受审批字符数据
	 */
	private String approvalChainJsonData;
	
	
    public Long getPageNum() {
		return pageNum;
	}

	public void setPageNum(Long pageNum) {
		this.pageNum = pageNum;
	}

	public Long getBeginIndex() {
		return beginIndex;
	}

	public void setBeginIndex(Long beginIndex) {
		this.beginIndex = beginIndex;
	}

	public Long getNumPerPage() {
		return numPerPage;
	}

	public void setNumPerPage(Long numPerPage) {
		this.numPerPage = numPerPage;
	}

	public List<SysOaTemplateTask> getOaTemplatetasks() {
		return oaTemplatetasks;
	}

	public void setOaTemplatetasks(List<SysOaTemplateTask> oaTemplatetasks) {
		this.oaTemplatetasks = oaTemplatetasks;
	}

	public String getApprovalChainJsonData() {
		return approvalChainJsonData;
	}

	public void setApprovalChainJsonData(String approvalChainJsonData) {
		this.approvalChainJsonData = approvalChainJsonData;
	}

	public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OA_OATEMPLATE.id
     *
     * @param id the value for OA_OATEMPLATE.id
     *
     * @mbggenerated Mon Aug 19 14:32:48 CST 2013
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OA_OATEMPLATE.code
     *
     * @return the value of OA_OATEMPLATE.code
     *
     * @mbggenerated Mon Aug 19 14:32:48 CST 2013
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OA_OATEMPLATE.code
     *
     * @param code the value for OA_OATEMPLATE.code
     *
     * @mbggenerated Mon Aug 19 14:32:48 CST 2013
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OA_OATEMPLATE.name
     *
     * @return the value of OA_OATEMPLATE.name
     *
     * @mbggenerated Mon Aug 19 14:32:48 CST 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OA_OATEMPLATE.name
     *
     * @param name the value for OA_OATEMPLATE.name
     *
     * @mbggenerated Mon Aug 19 14:32:48 CST 2013
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OA_OATEMPLATE.description
     *
     * @return the value of OA_OATEMPLATE.description
     *
     * @mbggenerated Mon Aug 19 14:32:48 CST 2013
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OA_OATEMPLATE.description
     *
     * @param description the value for OA_OATEMPLATE.description
     *
     * @mbggenerated Mon Aug 19 14:32:48 CST 2013
     */
    public void setDescription(String description) {
        this.description = description;
    }

      /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OA_OATEMPLATE.status
     *
     * @return the value of OA_OATEMPLATE.status
     *
     * @mbggenerated Mon Aug 19 14:32:48 CST 2013
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OA_OATEMPLATE.status
     *
     * @param status the value for OA_OATEMPLATE.status
     *
     * @mbggenerated Mon Aug 19 14:32:48 CST 2013
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OA_OATEMPLATE.MTime
     *
     * @return the value of OA_OATEMPLATE.MTime
     *
     * @mbggenerated Mon Aug 19 14:32:48 CST 2013
     */
    public Date getMtime() {
        return mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OA_OATEMPLATE.MTime
     *
     * @param mtime the value for OA_OATEMPLATE.MTime
     *
     * @mbggenerated Mon Aug 19 14:32:48 CST 2013
     */
    public void setMtime(Date mtime) {
        this.mtime = mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OA_OATEMPLATE.CTime
     *
     * @return the value of OA_OATEMPLATE.CTime
     *
     * @mbggenerated Mon Aug 19 14:32:48 CST 2013
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OA_OATEMPLATE.CTime
     *
     * @param ctime the value for OA_OATEMPLATE.CTime
     *
     * @mbggenerated Mon Aug 19 14:32:48 CST 2013
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

	public String getSystemcode() {
		return systemcode;
	}

	public void setSystemcode(String systemcode) {
		this.systemcode = systemcode;
	}

	public String getSystemName() {
		return systemName;
	}

	public void setSystemName(String systemName) {
		this.systemName = systemName;
	}
	
	private List<String> codes;


    public List<String> getCodes() {
        return codes;
    }

    public void setCodes(List<String> codes) {
        this.codes = codes;
    }
	
	
}