package com.td.admin.entity;

import java.util.Date;

public class SysOaTask {
	private Date findStartTime;
	private Date findEndTime;
	private String statusName;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OA_TASK.id
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OA_TASK.instanceId
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    private Long instanceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OA_TASK.taskId
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    private Long taskid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OA_TASK.taskCode
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    private String taskcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OA_TASK.taskName
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    private String taskname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OA_TASK.taskIndex
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    private Integer taskindex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OA_TASK.assignerUmId
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    private String assignerumid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OA_TASK.assignerName
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    private String assignername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OA_TASK.startTime
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    private Date starttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OA_TASK.endTime
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    private Date endtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OA_TASK.approve
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    private String approve;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OA_TASK.status
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OA_TASK.memo
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OA_TASK.MTime
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    private Date mtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OA_TASK.CTime
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    private Date ctime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OA_TASK.id
     *
     * @return the value of OA_TASK.id
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     * 
     * 	/**
     * 非数据库字段
     */
    private Long pageNum;
    
    private Long beginIndex;

	private Long numPerPage;
     
	private String instancename;
	
	
	
    public String getInstancename() {
		return instancename;
	}

	public void setInstancename(String instancename) {
		this.instancename = instancename;
	}

	public Long getPageNum() {
		return pageNum;
	}

	public void setPageNum(Long pageNum) {
		this.pageNum = pageNum;
	}

	public Long getBeginIndex() {
		return beginIndex;
	}

	public void setBeginIndex(Long beginIndex) {
		this.beginIndex = beginIndex;
	}

	public Long getNumPerPage() {
		return numPerPage;
	}

	public void setNumPerPage(Long numPerPage) {
		this.numPerPage = numPerPage;
	}

	public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OA_TASK.id
     *
     * @param id the value for OA_TASK.id
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OA_TASK.instanceId
     *
     * @return the value of OA_TASK.instanceId
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    public Long getInstanceid() {
        return instanceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OA_TASK.instanceId
     *
     * @param instanceid the value for OA_TASK.instanceId
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    public void setInstanceid(Long instanceid) {
        this.instanceid = instanceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OA_TASK.taskId
     *
     * @return the value of OA_TASK.taskId
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    public Long getTaskid() {
        return taskid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OA_TASK.taskId
     *
     * @param taskid the value for OA_TASK.taskId
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    public void setTaskid(Long taskid) {
        this.taskid = taskid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OA_TASK.taskCode
     *
     * @return the value of OA_TASK.taskCode
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    public String getTaskcode() {
        return taskcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OA_TASK.taskCode
     *
     * @param taskcode the value for OA_TASK.taskCode
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    public void setTaskcode(String taskcode) {
        this.taskcode = taskcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OA_TASK.taskName
     *
     * @return the value of OA_TASK.taskName
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    public String getTaskname() {
        return taskname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OA_TASK.taskName
     *
     * @param taskname the value for OA_TASK.taskName
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    public void setTaskname(String taskname) {
        this.taskname = taskname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OA_TASK.taskIndex
     *
     * @return the value of OA_TASK.taskIndex
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    public Integer getTaskindex() {
        return taskindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OA_TASK.taskIndex
     *
     * @param taskindex the value for OA_TASK.taskIndex
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    public void setTaskindex(Integer taskindex) {
        this.taskindex = taskindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OA_TASK.assignerUmId
     *
     * @return the value of OA_TASK.assignerUmId
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    public String getAssignerumid() {
        return assignerumid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OA_TASK.assignerUmId
     *
     * @param assignerumid the value for OA_TASK.assignerUmId
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    public void setAssignerumid(String assignerumid) {
        this.assignerumid = assignerumid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OA_TASK.assignerName
     *
     * @return the value of OA_TASK.assignerName
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    public String getAssignername() {
        return assignername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OA_TASK.assignerName
     *
     * @param assignername the value for OA_TASK.assignerName
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    public void setAssignername(String assignername) {
        this.assignername = assignername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OA_TASK.startTime
     *
     * @return the value of OA_TASK.startTime
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    public Date getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OA_TASK.startTime
     *
     * @param starttime the value for OA_TASK.startTime
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OA_TASK.endTime
     *
     * @return the value of OA_TASK.endTime
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OA_TASK.endTime
     *
     * @param endtime the value for OA_TASK.endTime
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OA_TASK.approve
     *
     * @return the value of OA_TASK.approve
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    public String getApprove() {
        return approve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OA_TASK.approve
     *
     * @param approve the value for OA_TASK.approve
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    public void setApprove(String approve) {
        this.approve = approve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OA_TASK.status
     *
     * @return the value of OA_TASK.status
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OA_TASK.status
     *
     * @param status the value for OA_TASK.status
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OA_TASK.memo
     *
     * @return the value of OA_TASK.memo
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OA_TASK.memo
     *
     * @param memo the value for OA_TASK.memo
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    public void setMemo(String memo) {
        this.memo = memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OA_TASK.MTime
     *
     * @return the value of OA_TASK.MTime
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    public Date getMtime() {
        return mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OA_TASK.MTime
     *
     * @param mtime the value for OA_TASK.MTime
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    public void setMtime(Date mtime) {
        this.mtime = mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OA_TASK.CTime
     *
     * @return the value of OA_TASK.CTime
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OA_TASK.CTime
     *
     * @param ctime the value for OA_TASK.CTime
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

	public Date getFindStartTime() {
		return findStartTime;
	}

	public void setFindStartTime(Date findStartTime) {
		this.findStartTime = findStartTime;
	}

	public Date getFindEndTime() {
		return findEndTime;
	}

	public void setFindEndTime(Date findEndTime) {
		this.findEndTime = findEndTime;
	}

	public String getStatusName() {
		return statusName;
	}

	public void setStatusName(String statusName) {
		this.statusName = statusName;
	}
}