package com.td.admin.entity;

import java.util.Date;

public class SysProcessTaskConfig {
	
//	private String iconurl;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_TASK_CONFIG.id
     *
     * @mbggenerated Wed Aug 21 10:18:24 CST 2013
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_TASK_CONFIG.name
     *
     * @mbggenerated Wed Aug 21 10:18:24 CST 2013
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_TASK_CONFIG.code
     *
     * @mbggenerated Wed Aug 21 10:18:24 CST 2013
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_TASK_CONFIG.timeoutRemindFlag
     *
     * @mbggenerated Wed Aug 21 10:18:24 CST 2013
     */
    private Integer timeoutremindflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_TASK_CONFIG.timeout
     *
     * @mbggenerated Wed Aug 21 10:18:24 CST 2013
     */
    private Integer timeout;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_TASK_CONFIG.serverUrl
     *
     * @mbggenerated Wed Aug 21 10:18:24 CST 2013
     */
//    private String pageurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_TASK_CONFIG.processConfigId
     *
     * @mbggenerated Wed Aug 21 10:18:24 CST 2013
     */
    private Long processconfigid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_TASK_CONFIG.remindInterval
     *
     * @mbggenerated Wed Aug 21 10:18:24 CST 2013
     */
    private Integer remindinterval;

    private String taskdescription;
    
    private String rolecode;
    
    private Long taskstartemailtemplateid;
    
    private Long taskendemailtemplateid;
    
    private String taskstartemailtemplatename;
    
    private String taskendemailtemplatename ; 
    
    private String processname ; 
    
    
    
    
    public String getTaskstartemailtemplatename() {
		return taskstartemailtemplatename;
	}

	public void setTaskstartemailtemplatename(String taskstartemailtemplatename) {
		this.taskstartemailtemplatename = taskstartemailtemplatename;
	}

	public String getTaskendemailtemplatename() {
		return taskendemailtemplatename;
	}

	public void setTaskendemailtemplatename(String taskendemailtemplatename) {
		this.taskendemailtemplatename = taskendemailtemplatename;
	}

	public String getRolecode() {
		return rolecode;
	}

	public void setRolecode(String rolecode) {
		this.rolecode = rolecode;
	}

	public Long getTaskstartemailtemplateid() {
		return taskstartemailtemplateid;
	}

	public void setTaskstartemailtemplateid(Long taskstartemailtemplateid) {
		this.taskstartemailtemplateid = taskstartemailtemplateid;
	}

	public Long getTaskendemailtemplateid() {
		return taskendemailtemplateid;
	}

	public void setTaskendemailtemplateid(Long taskendemailtemplateid) {
		this.taskendemailtemplateid = taskendemailtemplateid;
	}

	public String getProcessname() {
		return processname;
	}

	public void setProcessname(String processname) {
		this.processname = processname;
	}

 
	
	public String getTaskdescription() {
		return taskdescription;
	}

	public void setTaskdescription(String taskdescription) {
		this.taskdescription = taskdescription;
	}



	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_TASK_CONFIG.MTime
     *
     * @mbggenerated Wed Aug 21 10:18:24 CST 2013
     */
    
    private Date mtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_TASK_CONFIG.CTime
     *
     * @mbggenerated Wed Aug 21 10:18:24 CST 2013
     */
    private Date ctime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_TASK_CONFIG.id
     *
     * @return the value of FIN_TASK_CONFIG.id
     *
     * @mbggenerated Wed Aug 21 10:18:24 CST 2013
     */


	/**
     * 非数据库字段
     */
    private Long pageNum;
    
    private Long beginIndex;

	private Long numPerPage;
	
	
    public Long getPageNum() {
		return pageNum;
	}

	public void setPageNum(Long pageNum) {
		this.pageNum = pageNum;
	}

	public Long getBeginIndex() {
		return beginIndex;
	}

	public void setBeginIndex(Long beginIndex) {
		this.beginIndex = beginIndex;
	}

	public Long getNumPerPage() {
		return numPerPage;
	}

	public void setNumPerPage(Long numPerPage) {
		this.numPerPage = numPerPage;
	}

	public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_TASK_CONFIG.id
     *
     * @param id the value for FIN_TASK_CONFIG.id
     *
     * @mbggenerated Wed Aug 21 10:18:24 CST 2013
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_TASK_CONFIG.name
     *
     * @return the value of FIN_TASK_CONFIG.name
     *
     * @mbggenerated Wed Aug 21 10:18:24 CST 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_TASK_CONFIG.name
     *
     * @param name the value for FIN_TASK_CONFIG.name
     *
     * @mbggenerated Wed Aug 21 10:18:24 CST 2013
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_TASK_CONFIG.code
     *
     * @return the value of FIN_TASK_CONFIG.code
     *
     * @mbggenerated Wed Aug 21 10:18:24 CST 2013
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_TASK_CONFIG.code
     *
     * @param code the value for FIN_TASK_CONFIG.code
     *
     * @mbggenerated Wed Aug 21 10:18:24 CST 2013
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_TASK_CONFIG.timeoutRemindFlag
     *
     * @return the value of FIN_TASK_CONFIG.timeoutRemindFlag
     *
     * @mbggenerated Wed Aug 21 10:18:24 CST 2013
     */
    public Integer getTimeoutremindflag() {
        return timeoutremindflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_TASK_CONFIG.timeoutRemindFlag
     *
     * @param timeoutremindflag the value for FIN_TASK_CONFIG.timeoutRemindFlag
     *
     * @mbggenerated Wed Aug 21 10:18:24 CST 2013
     */
    public void setTimeoutremindflag(Integer timeoutremindflag) {
        this.timeoutremindflag = timeoutremindflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_TASK_CONFIG.timeout
     *
     * @return the value of FIN_TASK_CONFIG.timeout
     *
     * @mbggenerated Wed Aug 21 10:18:24 CST 2013
     */
    public Integer getTimeout() {
        return timeout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_TASK_CONFIG.timeout
     *
     * @param timeout the value for FIN_TASK_CONFIG.timeout
     *
     * @mbggenerated Wed Aug 21 10:18:24 CST 2013
     */
    public void setTimeout(Integer timeout) {
        this.timeout = timeout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_TASK_CONFIG.serverUrl
     *
     * @return the value of FIN_TASK_CONFIG.serverUrl
     *
     * @mbggenerated Wed Aug 21 10:18:24 CST 2013
     */
  
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_TASK_CONFIG.processConfigId
     *
     * @return the value of FIN_TASK_CONFIG.processConfigId
     *
     * @mbggenerated Wed Aug 21 10:18:24 CST 2013
     */
    public Long getProcessconfigid() {
        return processconfigid;
    }

//    public String getPageurl() {
//		return pageurl;
//	}
//
//	public void setPageurl(String pageurl) {
//		this.pageurl = pageurl;
//	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_TASK_CONFIG.processConfigId
     *
     * @param processconfigid the value for FIN_TASK_CONFIG.processConfigId
     *
     * @mbggenerated Wed Aug 21 10:18:24 CST 2013
     */
    public void setProcessconfigid(Long processconfigid) {
        this.processconfigid = processconfigid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_TASK_CONFIG.remindInterval
     *
     * @return the value of FIN_TASK_CONFIG.remindInterval
     *
     * @mbggenerated Wed Aug 21 10:18:24 CST 2013
     */
    public Integer getRemindinterval() {
        return remindinterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_TASK_CONFIG.remindInterval
     *
     * @param remindinterval the value for FIN_TASK_CONFIG.remindInterval
     *
     * @mbggenerated Wed Aug 21 10:18:24 CST 2013
     */
    public void setRemindinterval(Integer remindinterval) {
        this.remindinterval = remindinterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_TASK_CONFIG.MTime
     *
     * @return the value of FIN_TASK_CONFIG.MTime
     *
     * @mbggenerated Wed Aug 21 10:18:24 CST 2013
     */
    public Date getMtime() {
        return mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_TASK_CONFIG.MTime
     *
     * @param mtime the value for FIN_TASK_CONFIG.MTime
     *
     * @mbggenerated Wed Aug 21 10:18:24 CST 2013
     */
    public void setMtime(Date mtime) {
        this.mtime = mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_TASK_CONFIG.CTime
     *
     * @return the value of FIN_TASK_CONFIG.CTime
     *
     * @mbggenerated Wed Aug 21 10:18:24 CST 2013
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_TASK_CONFIG.CTime
     *
     * @param ctime the value for FIN_TASK_CONFIG.CTime
     *
     * @mbggenerated Wed Aug 21 10:18:24 CST 2013
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

//	public String getIconurl() {
//		return iconurl;
//	}
//
//	public void setIconurl(String iconurl) {
//		this.iconurl = iconurl;
//	}
}