package com.td.admin.entity;

import java.io.Serializable;
import java.util.Date;

public class SysParam implements Serializable{
	private static final long serialVersionUID = 1L;
	
	private Long rows;//分页
	private Long page;
	private Long beginIndex;
	private String systemName;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_SYSTEM_PARAM.id
     *
     * @mbggenerated Fri Aug 09 10:22:34 CST 2013
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_SYSTEM_PARAM.paramKey
     *
     * @mbggenerated Fri Aug 09 10:22:34 CST 2013
     */
    private String paramkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_SYSTEM_PARAM.paramValue
     *
     * @mbggenerated Fri Aug 09 10:22:34 CST 2013
     */
    private String paramvalue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_SYSTEM_PARAM.description
     *
     * @mbggenerated Fri Aug 09 10:22:34 CST 2013
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_SYSTEM_PARAM.pw
     *
     * @mbggenerated Fri Aug 09 10:22:34 CST 2013
     */
    private String pw;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_PROCESS_CONFIG.systemCode
     *
     * @mbggenerated Wed Aug 21 11:03:45 CST 2013
     */
    private String systemcode;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_SYSTEM_PARAM.MTime
     *
     * @mbggenerated Fri Aug 09 10:22:34 CST 2013
     */
    private Date mtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_SYSTEM_PARAM.CTime
     *
     * @mbggenerated Fri Aug 09 10:22:34 CST 2013
     */
    private Date ctime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_SYSTEM_PARAM.id
     *
     * @return the value of FIN_SYSTEM_PARAM.id
     *
     * @mbggenerated Fri Aug 09 10:22:34 CST 2013
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_SYSTEM_PARAM.id
     *
     * @param id the value for FIN_SYSTEM_PARAM.id
     *
     * @mbggenerated Fri Aug 09 10:22:34 CST 2013
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_SYSTEM_PARAM.paramKey
     *
     * @return the value of FIN_SYSTEM_PARAM.paramKey
     *
     * @mbggenerated Fri Aug 09 10:22:34 CST 2013
     */
    public String getParamkey() {
        return paramkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_SYSTEM_PARAM.paramKey
     *
     * @param paramkey the value for FIN_SYSTEM_PARAM.paramKey
     *
     * @mbggenerated Fri Aug 09 10:22:34 CST 2013
     */
    public void setParamkey(String paramkey) {
        this.paramkey = paramkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_SYSTEM_PARAM.paramValue
     *
     * @return the value of FIN_SYSTEM_PARAM.paramValue
     *
     * @mbggenerated Fri Aug 09 10:22:34 CST 2013
     */
    public String getParamvalue() {
        return paramvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_SYSTEM_PARAM.paramValue
     *
     * @param paramvalue the value for FIN_SYSTEM_PARAM.paramValue
     *
     * @mbggenerated Fri Aug 09 10:22:34 CST 2013
     */
    public void setParamvalue(String paramvalue) {
        this.paramvalue = paramvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_SYSTEM_PARAM.description
     *
     * @return the value of FIN_SYSTEM_PARAM.description
     *
     * @mbggenerated Fri Aug 09 10:22:34 CST 2013
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_SYSTEM_PARAM.description
     *
     * @param description the value for FIN_SYSTEM_PARAM.description
     *
     * @mbggenerated Fri Aug 09 10:22:34 CST 2013
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_SYSTEM_PARAM.pw
     *
     * @return the value of FIN_SYSTEM_PARAM.pw
     *
     * @mbggenerated Fri Aug 09 10:22:34 CST 2013
     */
    public String getPw() {
        return pw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_SYSTEM_PARAM.pw
     *
     * @param pw the value for FIN_SYSTEM_PARAM.pw
     *
     * @mbggenerated Fri Aug 09 10:22:34 CST 2013
     */
    public void setPw(String pw) {
        this.pw = pw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_SYSTEM_PARAM.MTime
     *
     * @return the value of FIN_SYSTEM_PARAM.MTime
     *
     * @mbggenerated Fri Aug 09 10:22:34 CST 2013
     */
    public Date getMtime() {
        return mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_SYSTEM_PARAM.MTime
     *
     * @param mtime the value for FIN_SYSTEM_PARAM.MTime
     *
     * @mbggenerated Fri Aug 09 10:22:34 CST 2013
     */
    public void setMtime(Date mtime) {
        this.mtime = mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_SYSTEM_PARAM.CTime
     *
     * @return the value of FIN_SYSTEM_PARAM.CTime
     *
     * @mbggenerated Fri Aug 09 10:22:34 CST 2013
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_SYSTEM_PARAM.CTime
     *
     * @param ctime the value for FIN_SYSTEM_PARAM.CTime
     *
     * @mbggenerated Fri Aug 09 10:22:34 CST 2013
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

	public String getSystemcode() {
		return systemcode;
	}

	public void setSystemcode(String systemcode) {
		this.systemcode = systemcode;
	}

	public String getSystemName() {
		return systemName;
	}

	public void setSystemName(String systemName) {
		this.systemName = systemName;
	}

	public Long getRows() {
		return rows;
	}

	public void setRows(Long rows) {
		this.rows = rows;
	}

	public Long getPage() {
		return page;
	}

	public void setPage(Long page) {
		this.page = page;
	}

	public Long getBeginIndex() {
		if((beginIndex==null||beginIndex<=0)&&page!=null&&rows!=null){
			beginIndex = (page-1)*rows;
		}
		return beginIndex;
	}

	public void setBeginIndex(Long beginIndex) {
		this.beginIndex = beginIndex;
	}
}