package com.td.admin.entity;

import java.io.Serializable;
import java.util.Date;

public class SysProcessConfig implements Serializable{
	private static final long serialVersionUID = 1L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_PROCESS_CONFIG.id
     *
     * @mbggenerated Wed Aug 21 11:03:45 CST 2013
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_PROCESS_CONFIG.name
     *
     * @mbggenerated Wed Aug 21 11:03:45 CST 2013
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_PROCESS_CONFIG.code
     *
     * @mbggenerated Wed Aug 21 11:03:45 CST 2013
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_PROCESS_CONFIG.version
     *
     * @mbggenerated Wed Aug 21 11:03:45 CST 2013
     */
    private String version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_PROCESS_CONFIG.systemCode
     *
     * @mbggenerated Wed Aug 21 11:03:45 CST 2013
     */
    private String systemcode;

    
    private String sysname ; 
    
  
	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_PROCESS_CONFIG.defaultTaskTimeout
     *
     * @mbggenerated Wed Aug 21 11:03:45 CST 2013
     */
    private Integer defaulttasktimeout;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_PROCESS_CONFIG.defaultRemindInterval
     *
     * @mbggenerated Wed Aug 21 11:03:45 CST 2013
     */
    private Integer defaultremindinterval;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_PROCESS_CONFIG.description
     *
     * @mbggenerated Wed Aug 21 11:03:45 CST 2013
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_PROCESS_CONFIG.processDefinitionViewUrl
     *
     * @mbggenerated Wed Aug 21 11:03:45 CST 2013
     */
    private String processdefinitionviewurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_PROCESS_CONFIG.MTime
     *
     * @mbggenerated Wed Aug 21 11:03:45 CST 2013
     */
    private Date mtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_PROCESS_CONFIG.CTime
     *
     * @mbggenerated Wed Aug 21 11:03:45 CST 2013
     */
    private Date ctime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_PROCESS_CONFIG.id
     *
     * @return the value of FIN_PROCESS_CONFIG.id
     *
     * @mbggenerated Wed Aug 21 11:03:45 CST 2013
     */
    /**
     * 非数据库字段
     */
    private Long pageNum;
    
    private Long beginIndex;

	private Long numPerPage;
	
	
    
    public Long getPageNum() {
		return pageNum;
	}

	public void setPageNum(Long pageNum) {
		this.pageNum = pageNum;
	}

	public Long getBeginIndex() {
		return beginIndex;
	}

	public void setBeginIndex(Long beginIndex) {
		this.beginIndex = beginIndex;
	}

	public Long getNumPerPage() {
		return numPerPage;
	}

	public void setNumPerPage(Long numPerPage) {
		this.numPerPage = numPerPage;
	}

	public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_PROCESS_CONFIG.id
     *
     * @param id the value for FIN_PROCESS_CONFIG.id
     *
     * @mbggenerated Wed Aug 21 11:03:45 CST 2013
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_PROCESS_CONFIG.name
     *
     * @return the value of FIN_PROCESS_CONFIG.name
     *
     * @mbggenerated Wed Aug 21 11:03:45 CST 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_PROCESS_CONFIG.name
     *
     * @param name the value for FIN_PROCESS_CONFIG.name
     *
     * @mbggenerated Wed Aug 21 11:03:45 CST 2013
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_PROCESS_CONFIG.code
     *
     * @return the value of FIN_PROCESS_CONFIG.code
     *
     * @mbggenerated Wed Aug 21 11:03:45 CST 2013
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_PROCESS_CONFIG.code
     *
     * @param code the value for FIN_PROCESS_CONFIG.code
     *
     * @mbggenerated Wed Aug 21 11:03:45 CST 2013
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_PROCESS_CONFIG.version
     *
     * @return the value of FIN_PROCESS_CONFIG.version
     *
     * @mbggenerated Wed Aug 21 11:03:45 CST 2013
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_PROCESS_CONFIG.version
     *
     * @param version the value for FIN_PROCESS_CONFIG.version
     *
     * @mbggenerated Wed Aug 21 11:03:45 CST 2013
     */
    public void setVersion(String version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_PROCESS_CONFIG.systemCode
     *
     * @return the value of FIN_PROCESS_CONFIG.systemCode
     *
     * @mbggenerated Wed Aug 21 11:03:45 CST 2013
     */
    public String getSystemcode() {
        return systemcode;
    }
    
    public String getSysname() {
		return sysname;
	}

	public void setSysname(String sysname) {
		this.sysname = sysname;
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_PROCESS_CONFIG.systemCode
     *
     * @param systemcode the value for FIN_PROCESS_CONFIG.systemCode
     *
     * @mbggenerated Wed Aug 21 11:03:45 CST 2013
     */
    public void setSystemcode(String systemcode) {
        this.systemcode = systemcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_PROCESS_CONFIG.defaultTaskTimeout
     *
     * @return the value of FIN_PROCESS_CONFIG.defaultTaskTimeout
     *
     * @mbggenerated Wed Aug 21 11:03:45 CST 2013
     */
    public Integer getDefaulttasktimeout() {
        return defaulttasktimeout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_PROCESS_CONFIG.defaultTaskTimeout
     *
     * @param defaulttasktimeout the value for FIN_PROCESS_CONFIG.defaultTaskTimeout
     *
     * @mbggenerated Wed Aug 21 11:03:45 CST 2013
     */
    public void setDefaulttasktimeout(Integer defaulttasktimeout) {
        this.defaulttasktimeout = defaulttasktimeout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_PROCESS_CONFIG.defaultRemindInterval
     *
     * @return the value of FIN_PROCESS_CONFIG.defaultRemindInterval
     *
     * @mbggenerated Wed Aug 21 11:03:45 CST 2013
     */
    public Integer getDefaultremindinterval() {
        return defaultremindinterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_PROCESS_CONFIG.defaultRemindInterval
     *
     * @param defaultremindinterval the value for FIN_PROCESS_CONFIG.defaultRemindInterval
     *
     * @mbggenerated Wed Aug 21 11:03:45 CST 2013
     */
    public void setDefaultremindinterval(Integer defaultremindinterval) {
        this.defaultremindinterval = defaultremindinterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_PROCESS_CONFIG.description
     *
     * @return the value of FIN_PROCESS_CONFIG.description
     *
     * @mbggenerated Wed Aug 21 11:03:45 CST 2013
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_PROCESS_CONFIG.description
     *
     * @param description the value for FIN_PROCESS_CONFIG.description
     *
     * @mbggenerated Wed Aug 21 11:03:45 CST 2013
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_PROCESS_CONFIG.processDefinitionViewUrl
     *
     * @return the value of FIN_PROCESS_CONFIG.processDefinitionViewUrl
     *
     * @mbggenerated Wed Aug 21 11:03:45 CST 2013
     */
    public String getProcessdefinitionviewurl() {
        return processdefinitionviewurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_PROCESS_CONFIG.processDefinitionViewUrl
     *
     * @param processdefinitionviewurl the value for FIN_PROCESS_CONFIG.processDefinitionViewUrl
     *
     * @mbggenerated Wed Aug 21 11:03:45 CST 2013
     */
    public void setProcessdefinitionviewurl(String processdefinitionviewurl) {
        this.processdefinitionviewurl = processdefinitionviewurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_PROCESS_CONFIG.MTime
     *
     * @return the value of FIN_PROCESS_CONFIG.MTime
     *
     * @mbggenerated Wed Aug 21 11:03:45 CST 2013
     */
    public Date getMtime() {
        return mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_PROCESS_CONFIG.MTime
     *
     * @param mtime the value for FIN_PROCESS_CONFIG.MTime
     *
     * @mbggenerated Wed Aug 21 11:03:45 CST 2013
     */
    public void setMtime(Date mtime) {
        this.mtime = mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_PROCESS_CONFIG.CTime
     *
     * @return the value of FIN_PROCESS_CONFIG.CTime
     *
     * @mbggenerated Wed Aug 21 11:03:45 CST 2013
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_PROCESS_CONFIG.CTime
     *
     * @param ctime the value for FIN_PROCESS_CONFIG.CTime
     *
     * @mbggenerated Wed Aug 21 11:03:45 CST 2013
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }
}