package com.td.admin.entity;

public class SysSequenceSub {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_SEQUENCE_SHEET.seq_sheet_name
     *
     * @mbggenerated Thu Jan 16 15:31:41 CST 2014
     */
    private String seqSubName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_SEQUENCE_SHEET.current_value
     *
     * @mbggenerated Thu Jan 16 15:31:41 CST 2014
     */
    private Integer currentValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_SEQUENCE_SHEET.increment
     *
     * @mbggenerated Thu Jan 16 15:31:41 CST 2014
     */
    private Integer increment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_SEQUENCE_SHEET.remark
     *
     * @mbggenerated Thu Jan 16 15:31:41 CST 2014
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_SEQUENCE_SHEET.seq_sheet_name
     *
     * @return the value of FIN_SEQUENCE_SHEET.seq_sheet_name
     *
     * @mbggenerated Thu Jan 16 15:31:41 CST 2014
     */
    public String getSeqSubName() {
        return seqSubName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_SEQUENCE_SHEET.seq_sheet_name
     *
     * @param seqSubName the value for FIN_SEQUENCE_SHEET.seq_sheet_name
     *
     * @mbggenerated Thu Jan 16 15:31:41 CST 2014
     */
    public void setSeqSubName(String seqSubName) {
        this.seqSubName = seqSubName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_SEQUENCE_SHEET.current_value
     *
     * @return the value of FIN_SEQUENCE_SHEET.current_value
     *
     * @mbggenerated Thu Jan 16 15:31:41 CST 2014
     */
    public Integer getCurrentValue() {
        return currentValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_SEQUENCE_SHEET.current_value
     *
     * @param currentValue the value for FIN_SEQUENCE_SHEET.current_value
     *
     * @mbggenerated Thu Jan 16 15:31:41 CST 2014
     */
    public void setCurrentValue(Integer currentValue) {
        this.currentValue = currentValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_SEQUENCE_SHEET.increment
     *
     * @return the value of FIN_SEQUENCE_SHEET.increment
     *
     * @mbggenerated Thu Jan 16 15:31:41 CST 2014
     */
    public Integer getIncrement() {
        return increment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_SEQUENCE_SHEET.increment
     *
     * @param increment the value for FIN_SEQUENCE_SHEET.increment
     *
     * @mbggenerated Thu Jan 16 15:31:41 CST 2014
     */
    public void setIncrement(Integer increment) {
        this.increment = increment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_SEQUENCE_SHEET.remark
     *
     * @return the value of FIN_SEQUENCE_SHEET.remark
     *
     * @mbggenerated Thu Jan 16 15:31:41 CST 2014
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_SEQUENCE_SHEET.remark
     *
     * @param remark the value for FIN_SEQUENCE_SHEET.remark
     *
     * @mbggenerated Thu Jan 16 15:31:41 CST 2014
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    private String connectSign;

    private Integer curValue;
    
	public String getConnectSign() {
		return connectSign;
	}

	public void setConnectSign(String connectSign) {
		this.connectSign = connectSign;
	}

	public Integer getCurValue() {
		return curValue;
	}

	public void setCurValue(Integer curValue) {
		this.curValue = curValue;
	}
}