package com.td.admin.entity;

public class SysSequence {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_SEQUENCE.seq_name
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    private String seqName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_SEQUENCE.current_value
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    private Integer currentValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_SEQUENCE.increment
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    private Integer increment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_SEQUENCE.remark
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_SEQUENCE.seq_name
     *
     * @return the value of FIN_SEQUENCE.seq_name
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    public String getSeqName() {
        return seqName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_SEQUENCE.seq_name
     *
     * @param seqName the value for FIN_SEQUENCE.seq_name
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    public void setSeqName(String seqName) {
        this.seqName = seqName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_SEQUENCE.current_value
     *
     * @return the value of FIN_SEQUENCE.current_value
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    public Integer getCurrentValue() {
        return currentValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_SEQUENCE.current_value
     *
     * @param currentValue the value for FIN_SEQUENCE.current_value
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    public void setCurrentValue(Integer currentValue) {
        this.currentValue = currentValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_SEQUENCE.increment
     *
     * @return the value of FIN_SEQUENCE.increment
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    public Integer getIncrement() {
        return increment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_SEQUENCE.increment
     *
     * @param increment the value for FIN_SEQUENCE.increment
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    public void setIncrement(Integer increment) {
        this.increment = increment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_SEQUENCE.remark
     *
     * @return the value of FIN_SEQUENCE.remark
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_SEQUENCE.remark
     *
     * @param remark the value for FIN_SEQUENCE.remark
     *
     * @mbggenerated Tue Aug 27 09:24:25 CST 2013
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}