package com.td.admin.entity;

import java.util.Date;

import org.codehaus.jackson.map.annotate.JsonSerialize;
import org.springframework.format.annotation.DateTimeFormat;

import com.talkingdata.jackson.JacksonCustomDate2Serializer;
import com.talkingdata.jackson.JacksonCustomDateSerializer;

public class SysTakeover {
	 private String type;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_SALES_TAKEOVERSETTING.id
     *
     * @mbggenerated Tue Aug 13 14:35:10 CST 2013
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_SALES_TAKEOVERSETTING.userUmId
     *
     * @mbggenerated Tue Aug 13 14:35:10 CST 2013
     */
    private String userumid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_SALES_TAKEOVERSETTING.targetUserUmId
     *
     * @mbggenerated Tue Aug 13 14:35:10 CST 2013
     */
    private String targetuserumid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_SALES_TAKEOVERSETTING.startTime
     *
     * @mbggenerated Tue Aug 13 14:35:10 CST 2013
     */
    private Date starttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_SALES_TAKEOVERSETTING.endTime
     *
     * @mbggenerated Tue Aug 13 14:35:10 CST 2013
     */
    private Date endtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_SALES_TAKEOVERSETTING.MTime
     *
     * @mbggenerated Tue Aug 13 14:35:10 CST 2013
     */
    private Date mtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIN_SALES_TAKEOVERSETTING.CTime
     *
     * @mbggenerated Tue Aug 13 14:35:10 CST 2013
     */
    private Date ctime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_SALES_TAKEOVERSETTING.id
     *
     * @return the value of FIN_SALES_TAKEOVERSETTING.id
     *
     * @mbggenerated Tue Aug 13 14:35:10 CST 2013
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_SALES_TAKEOVERSETTING.id
     *
     * @param id the value for FIN_SALES_TAKEOVERSETTING.id
     *
     * @mbggenerated Tue Aug 13 14:35:10 CST 2013
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_SALES_TAKEOVERSETTING.userUmId
     *
     * @return the value of FIN_SALES_TAKEOVERSETTING.userUmId
     *
     * @mbggenerated Tue Aug 13 14:35:10 CST 2013
     */
    public String getUserumid() {
        return userumid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_SALES_TAKEOVERSETTING.userUmId
     *
     * @param userumid the value for FIN_SALES_TAKEOVERSETTING.userUmId
     *
     * @mbggenerated Tue Aug 13 14:35:10 CST 2013
     */
    public void setUserumid(String userumid) {
        this.userumid = userumid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_SALES_TAKEOVERSETTING.targetUserUmId
     *
     * @return the value of FIN_SALES_TAKEOVERSETTING.targetUserUmId
     *
     * @mbggenerated Tue Aug 13 14:35:10 CST 2013
     */
    public String getTargetuserumid() {
        return targetuserumid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_SALES_TAKEOVERSETTING.targetUserUmId
     *
     * @param targetuserumid the value for FIN_SALES_TAKEOVERSETTING.targetUserUmId
     *
     * @mbggenerated Tue Aug 13 14:35:10 CST 2013
     */
    public void setTargetuserumid(String targetuserumid) {
        this.targetuserumid = targetuserumid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_SALES_TAKEOVERSETTING.startTime
     *
     * @return the value of FIN_SALES_TAKEOVERSETTING.startTime
     *
     * @mbggenerated Tue Aug 13 14:35:10 CST 2013
     */
    @JsonSerialize(using = JacksonCustomDateSerializer.class)
    public Date getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_SALES_TAKEOVERSETTING.startTime
     *
     * @param starttime the value for FIN_SALES_TAKEOVERSETTING.startTime
     *
     * @mbggenerated Tue Aug 13 14:35:10 CST 2013
     */
    @DateTimeFormat(pattern="yyyy-MM-dd")
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_SALES_TAKEOVERSETTING.endTime
     *
     * @return the value of FIN_SALES_TAKEOVERSETTING.endTime
     *
     * @mbggenerated Tue Aug 13 14:35:10 CST 2013
     */
    @JsonSerialize(using = JacksonCustomDateSerializer.class)
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_SALES_TAKEOVERSETTING.endTime
     *
     * @param endtime the value for FIN_SALES_TAKEOVERSETTING.endTime
     *
     * @mbggenerated Tue Aug 13 14:35:10 CST 2013
     */
    @DateTimeFormat(pattern="yyyy-MM-dd")
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_SALES_TAKEOVERSETTING.MTime
     *
     * @return the value of FIN_SALES_TAKEOVERSETTING.MTime
     *
     * @mbggenerated Tue Aug 13 14:35:10 CST 2013
     */
    @JsonSerialize(using = JacksonCustomDate2Serializer.class)
    public Date getMtime() {
        return mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_SALES_TAKEOVERSETTING.MTime
     *
     * @param mtime the value for FIN_SALES_TAKEOVERSETTING.MTime
     *
     * @mbggenerated Tue Aug 13 14:35:10 CST 2013
     */
    @DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
    public void setMtime(Date mtime) {
        this.mtime = mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIN_SALES_TAKEOVERSETTING.CTime
     *
     * @return the value of FIN_SALES_TAKEOVERSETTING.CTime
     *
     * @mbggenerated Tue Aug 13 14:35:10 CST 2013
     */
    @JsonSerialize(using = JacksonCustomDate2Serializer.class)
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIN_SALES_TAKEOVERSETTING.CTime
     *
     * @param ctime the value for FIN_SALES_TAKEOVERSETTING.CTime
     *
     * @mbggenerated Tue Aug 13 14:35:10 CST 2013
     */
    @DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}
}